label camilletalk:
    if camillelvl == 1:
        play music "sounds/armoir.mp3" fadeout 1
        if talkcamille:
            scene black
            scene cam-2 with fade
            p "Hey Camille, we've met before!"
            scene cam-1
            t "...[p]?"
            t "I didn't think I'd see you again."
            p "The town's not too big, I was sure we'd bump into each other again."
            scene cam-3
            t "You... weren't answering my texts and I thought the worst..."
            p "Oh yeah! I gave you my number!"
            p "I'm so sorry Camille, I totally forgot. I actually sold my phone because I needed some money!"
            p "I'll have to get a new one sometime."
            scene cam-2
            t "Oh I see... sorry for assuming."
            p "No, no that's alright."
            p "Anyway, what's happening here?"
            scene cam-4 with dissolve
            t "Oh, sorry I got distracted from my job again!"
            scene cam-5 with dissolve
            t "This is the luxury resort! We have many different kinds of facilities here."
            $ camillelvl += 1
            $ camilletalk = day
            jump Camille
        scene black
        scene cam-2 with fade
        p "Hey."
        p "I think we've met before."
        scene cam-1
        x "Oh, we met at the shopping mall..."
        p "Did you have any luck finding Vincent?"
        scene cam-3
        x "Ah... I must have just missed him..."
        "(Yeah, thought so.)"
        p "So, what's your name?"
        scene cam-3
        t "It's Camille. And you?"
        p "The name's [p]."
        scene cam-5
        t "[p]. I like that name."
        p "Anyway, what's happening here?"
        scene cam-4 with dissolve
        t "Oh, sorry I got distracted from my job again!"
        scene cam-5 with dissolve
        t "This is the luxury resort! We have many different kinds of facilities here."
        $ camillelvl += 1
        $ camilletalk = day
        jump Camille
    if camillelvl == 2:
        p "Hello Camille!"
        t "H-hey [p]."
        t "Is there somwhere where you'd like to go? Something I can help you with?"
        p "Nothing right now, I was just wondering how you're doing."
        p "Remember when we first met? You seemed to have your mind full with something, and I haven't asked you about that since then."
        t "Oh, that wasn't anything, really!"
        p "You sure?"
        t "Umm..."
        p "Hey, how about this?"
        p "Let's go off somewhere, and we'll have a man to man- I mean, man to woman talk."
        t "I- I'm working right now, I couldn't just go off- I mean, I'd love to, but still!"
        p "I think people are gonna be alright here. If someone comes, they'll ring the bell, right?"
        t "I.. suppose."
        t "But where are we going?"
        p "You know this place better than I do, why don't you show me around the VIP or staff areas!"
        t "I can't get you into the VIP, or I'll get into trouble. But maybe... we can talk after work?"
        t "Why don't you relax in the sauna, and I'll just come find you later?"
        p "The sauna. Right. Do I need the membership?"
        t "I'd love to let you in for free... but it's hard... I hope you understand?"
        p "I won't put you through any drama Camille. Don't worry. I need the silver membership right?"
        t "That's right!"
        p "Hold up, let me check to see if I have it."
        "Hmm, let me see..."
        $ camillelvl += 1
        jump lobby
    if camillelvl == 3:
        if resortmembership > 1:
            p "Yup, I'm a member. May I go to the sauna?"
            t "Of course. Let me take you."
            t "Welcome to the sauna. Do enjoy your stay here for a bit."
            p "Do come and say hi after work and we'll talk then."
            t "I'll make sure to do that, [p]. Thank you."
            "Time to get changed."
            "I admit, I am a little curious about Camille. She always seems so shy, I'm little surprised she's meeting me afterwards."
            "Is this going to be like a date or something?"
            "Ah, shouldn't think too much about it [p]. We'll see."
            "The sauna is actually so nice. I rarely come to these sort of things but it's a great place to relax."
            "The hot steam is making me feel sleepy..."
            "..."
            "zzzzz...."
            play music "sounds/cyberpunk.mp3" fadeout 1
            x "Are you fancying Camille, [p]?"
            p "You, always in my dreams."
            x "Camille was rejected by Vincent. Will you reject Camille too?"
            p "A little too soon to say, don't you think?"
            p "She seems a nice girl. I have nothing against her."
            x "One day, you find out why you made a choice."
            p "What choice?"
            x "Which choice is more depraved? I'll leave that for you to find out."
            p "Why don't you ever answer my damn questions."
            p "Being all mysterious and shit."
            stop music fadeout 1
            x "It's time to wake up."
            p "Ah!"
            "{i}Pant... pant{/i}*"
            "I hear someone coming in. Is it Camille?"
            "God how long was I out for?"
            t "Um, [p]?"
            play music "sounds/slopes.mp3"
            p "Here."
            t "I'm done with work now, you said you wanted to have a meet up and have a chat?"
            p "Yeah, I did say that. The sauna was so relaxing, I lost track of time."
            p "Hang on, just let me get changed. Should I meet you back at the reception?"
            t "Yes, I'll meet you back there."
            "Shit, I casually suggested a chat and now it seems like something serious."
            "I'm just a lucky guy."
            scene black with fade
            "Ah, back in my Kishou Arima outfit."
            t "Hello [p]."
            p "Oh hey Camille. I was just thinking of catching up."
            p "I've been meaning to meet up with you like I promised. Sorry again for not calling you, haha."
            p "So this seems serious. We should do something to fit the occassion. Where do you want to go?"
            t "Are you... are you feeling hungry?"
            "Yeah, hungry for action."
            p "I'm not too hungry, but I'll be keen for food still."
            t "In that case, how about we go to the bar?"
            p "Hmm, it's like we're coming full circle."
            p "Should we go now?"
            t "Um, I've got a few things I've got to handle at home first. How about I meet you there?"
            p "Sure, I'll wait there for you."
            ## transition to bar
            play music "sounds/popstars.mp3" fadeout 1
            "Hm, I wonder how long she will take."
            "Girls always take ages, wonder if Camille will be any different."
            p "Hey Caroline, how is it going?"
            c "Good, [p], good!"
            c "Coming to the bar for a few drinks?"
            p "Yes, and I brought a friend this time!"
            c "A {i}girl{/i}-friend?"
            p "Aha, don't be silly. It's Camille. She's come here before, I'm sure you know her."
            c "Ah. Camille! Yes, I've come to know her pretty well over a period."
            p "Just thought I'd catch up with her."
            c "How again do you know her?"
            p "Well, I saw her in the bar here with you, rememeber? When I first came?"
            p "I met her before though to be honest. Poor girl was chasing after a guy who wasn't too keen on her."
            c "I see."
            p "His loss, am I right?"
            c "I think she's a great person and she'll find someone someday."
            c "So how is it that you two are meeting today?"
            p "I just saw that she was feeling a bit down, so I wanted to catch up with her and make sure she's okay."
            p "Anyway, I'm keen to always make new friends."
            c "That's good to hear, [p]."
            c "It looks like you won't have to wait much longer, she's here."
            ## bar scene
            p "Camille!"
            play music "sounds/armoir.mp3" fadeout 1
            "It looks like she went home to change her outfit and her look. It's very cute and it's nice seeing her out of her working attire."
            p "The last time we were here- how long ago was that?"
            p "You're looking great by the way."
            t "Ah-thank you, [p]!"
            # fade to seat
            t "Hello Caroline."
            t "I hope your work isn't keeping you too busy!"
            c "I never mind if it's customers like yourselves."
            c "Can I help you two to a few drinks?"
            p "Camille?"
            t "I'm always fond of Dante's original."
            p "Me too. Let's go for that Caroline."
            c "I knew you'd say that. Coming right up!"
            p "You come here a lot, Camille?"
            t "I... come here sometimes."
            t "I like to see Caroline and the drinks here are nice."
            p "Are you good at handling your alcohol?"
            t "I was never any good, ah-"
            p "Reminds me of my [sr]. You know, she was here that night we were here last. Did you see her?"
            t "Ah, I must have left before she came."
            p "Oh that's right, you had to leave for something early back then. I hope that ended up being alright."
            t "Ah yes, I- I managed to sort it out."
            p "So tell me something about yourself, Camille."
            t "Err, well I work at the resort, and I enjoy it."
            p "Do you get any perks?"
            t "I have access to all the areas for free."
            p "Hey, that's pretty awesome."
            p "What do you like to do the most at the resort?"
            t "There's an area with a hot spring. I like going there late at night and bathe with while looking at the stars."
            p "That sounds quite romantic, actually."
            p "Are there many people there at night?"
            t "No, it's closed at that time so it's just me. It's the fact that I'm alone that I like so much."
            p "I can imagine that it would be relaxing."
            t "What about you? What do you like to do?"
            menu:
                "I like meeting girls.":
                    $ depravity += 1
                    t "Aha..."
                "I like going to the resort.":
                    t "Oh, ah- I'm glad to see you come to the resort too."
                    p "Oh, I mean I like to swim and stuff but of course I like to see you too at the resort."
                    t "Ah- I... sorry, forget I said that."
            p "You know, you don't have to talk about it if you don't want to, but what was going on the day I first met you?"
            p "You were looking for a guy called... Vincent?"
            t "..."
            t "We used to meet up a bit, and one day, he became more distant."
            ## drinks more
            t "Caroline, may I have one more drink?"
            c "Of course Camille!"
            "Hmm, she's started to drink more heavily after I brought up Vincent. I wonder what's going on there."
            p "Sorry to bring it up."
            t "Mm."
            t "It's okay, it's in the past."
            p "So, what else do you do in your free time?"
            t "Umm... I also like to draw."
            p "You're quite artistic then, aren't you?"
            p "What do you draw?"
            t "All sorts of things. There's an art class nearby."
            p "How's the art class?"
            t "I like it, it taught me the basic skills that I needed."
            t "More often though, I go in by myself to make drawings."
            p "What was the last thing you drew?"
            t "I drew a woman."
            p "You draw people often?"
            t "Well, I like just putting down on canvas the figures in my mind."
            t "So it could be anything really. Some days it can be nature, the other days people."
            p "You should show me around the class one day."
            t "I will! That should be fun."
            p "You know, we're in a club."
            t "Yes?"
            p "People usually dance in clubs."
            t "Oh! I-"
            p "Come on now, don't be shy!"
            p "Show us a few moves."
            t "Aha, [p], please-!"
            p "You've had a few drinks already, you should be all loosened up by now!"
            t "I really can't dance!"
            p "Oh, alright then. You get off this time."
            p "But next time- alright?"
            t "Next... time?"
            p "Yeah. Next time."
            p "For our next date."
            t "Ahh..."
            p "To get to know each other better."
            "I'm not stealing Vincent's girl, right? They weren't working out anyway."
            t "Okay!"
            t "..."
            t "Would you..."
            t "Would you like to come around, to... for me to show you around my house?"
            p "Is it a big house?"
            t "It's.. decently sized?"
            p "I'd love to Camille. I'm real curious where you live."
            t "It's one of the guest suites in the resort - I'm lucky enough to be able to live there."
            t "Okay, come with me."
            ## to house
            p "Wow, this is your place?"
            p "It's got a real modern aesthetic."
            p "What the hell, you're doing alright for yourself!"
            t "It's because I work at the resort- I can stay here for cheap."
            p "I could really get comfortable here."
            p "Wow, a pool too?"
            p "Jesus."
            t "I'm happy you like it. Are you hungry?"
            p "A little, we didn't actually grab anything to eat at the bar, and alcohol is never good on an empty stomach!"
            p "You got some snacks?"
            t "Hmm, I don't have a lot in stock, but I do have some noodles."
            p "Cup noodles?"
            t "Yes."
            p "Perfect."
            t "Just hang on a moment."
            t "Make yourself at home."
            p "Thank you."
            "Wow, this place is so nice, and this is just the living room!"
            "If Camille didn't get to live here for cheap, this place would cost a ton."
            "I wonder if I could ever afford a place like this."
            "Maybe if I hit big on the crypto coins huh?"
            "Since Camille's invited me to her house, does this mean she's okay with the idea of going out with me?"
            "Fuck knows."
            "She's such a cute girl. I get that Vincent might not like her, but did he have to run away?"
            "I don't feel good asking her about it. I'll just have to chat with Vincent afterwards."
            t "(I hope he's looking at me.)"
            t "(Maybe he likes me.)"
            t "(Someone, finally, maybe.)"
            t "(Someone to love me for me.)"
            ## exchange glances and smiles
            t "(He is.)"
            t "Delicious cup noodles- on their way."
            p "It's everyone's favourite."
            p "Something so simple yet so good."
            t "Mmmm..."
            p "You know, your life must be so good."
            t "..."
            p "You get to work at the resort, where you get to access everything."
            p "At home you get to come back to this awesome house."
            p "If I could own something like this in the future, I'd have made it."
            t "Things aren't always what they look like though, on the surface."
            p "That's true. There's always more than meets the eye."
            p "So what's your secret?"
            t "Some things you can only learn by being close somebody."
            t "I like this house, but it feels empty."
            t "There's something... missing."
            p "Not feeling too lonely are we?"
            t "Not as much as before."
            p "Well, I'm an extra body to keep you warm."
            t "..."
            p "Come here."
            t "...[p]?"
            ## kiss
            "First base."
            p "With a bit of alcohol, you really do come out of your shell don't you?"
            t "..."
            t "I-"
            p "It's alright."
            t "Thank you for that. I... liked it."
            t "Do you- do you want me to..."
            p "Hmmm?"
            t "Let me...let me do something for you."
            p "What are you thinking?"
            t "I can... I can return the favour."
            "She looked down suggestively."
            "Shit, this is uncharacteristically quick."
            menu:
                "I'm not going to say no.":
                    $ depravity += 1
                    # bj
                    "Acting in a way that nobody could have imagined, she got down gingerly on her knees."
                    "Expert hands that did not belong to her pulled out my tightening penis."
                    p "Heh, seen one before, Camille?"
                    t "Yes... yes I have."
                    "She took a look at it and I could tell there was a deep hunger behind those eyes, but also, something to prove."
                    "To become so intimate with someone like her so quickly, I could not ever imagine."
                    "There is something more to her, definitely, than meets the eye."
                    "And then she took me."
                    t "Mmmm."
                    p "Argh."
                    p "You're so damn good, Camille."
                    p "How did you get so good?!"
                    "She sucked my cock with expert technique that she had no right in knowing."
                    "It seemed like she knew exactly where a penis is most sensitive."
                    "She knew how a penis worked like it was the back of her hand."
                    "Her tongue carressed the underside of my shaft and I took her a lot more seriously."
                    p "At this rate, Camille, I don't know how much longer I'll last!"
                    menu:
                        "Swallow me.":
                            p "Argh!"
                        "Spread me all over your face.":
                            p "Argh!"
                    p "That was good. Are you alright Camille?"
                    p "...Camille?"
                    t "I..."
                    t "Sorry I'm feeling a bit tired, I need to rest now."
                    p "Are you feeling okay?"
                    t "I'll see you again tomorrow okay? I just..."
                    t "I'm not feeling too well and I need to rest."
                    p "I'm sorry if it's anything I did."
                    t "Don't be! I just-"
                    t "Please, I just need some time to myself."
                    t "I still want to see you again though. I'll see you tomorrow okay?"
                    t "Nothing went wrong... Like I said, I just need some time."
                    p "... Alright Camille, I respect that. I also want to see you again sometime."
                    p "We were moving a bit too quickly, I think."
                    t "I'm sorry to end the night quick. I do like you, [p]."
                    t "There's just something I need to think about."
                    p "By all means."
                    p "I'll see you tomorrow again, okay?"
                    t "Thank you [p]. Goodnight!"
                    p "Take care."
                "You're drunk Camille, I don't think you should.":
                    t "Ah, of course, I-"
                    t "I... got carried away."
                    p "It's not your fault, I just don't want to take advantage of you."
                    t "Thank you, [p]."
                    p "Um, you know what? It's probably best I head off now."
                    p "I do want to see you again, though."
                    t "I'm sorry about that, [p]."
                    p "Don't be, Camille. I appreciate it, but I don't want you to regret it tomorrow, haha."
                    p "I'll come chat you up again at the resort soon, alright?"
                    t "Okay!"
                    p "Take care, Camille."
                    t "Goodnight, [p]!"
            stop music fadeout 1
            "That was a little strange."
            "Just a little."
            "I think it'd be a good idea to call Vincent and just see what's up."
            "*Ring ring..."
            v "Hey there, Vincent here. Professional photography, modelling services and more. How can I help?"
            p "Hey Vince, it's me, [p]."
            v "Thought you'd never call. How's it going brother?"
            p "Listen, it's late and I'll cut to the chase. It's about that chick Camille."
            v "Huh?"
            p "She's the one you were trying to run away from."
            v "Oh I remember. Just a little unexpected that you want to chat about her."
            p "Are you free sometime?"
            v "This sounds like an emergency, what's up?"
            p "It's a little important. How about we catch up and I'll tell you all about it?"
            v "..."
            v "Alright."
            v "Let's meet up tomorrow morning at the Ice Cream Parlour."
            p "...sure."
            v "I'll see you then."
            p "See you."
            ## The next day...
            "(THE NEXT DAY...)"
            play music "sounds/wistful.mp3" fadeout 1
            "Hmm, it looks like I got here first."
            "This is an interesting place. I wonder if Vincent chose it for any reason."
            "Guess he likes sucking on popsicles hahaha."
            v "Hey!"
            v "Nice to see you again buddy."
            p "Thanks for meeting up with me on such short notice."
            v "No problem. How are you doing anyway?"
            p "I'm good man, I'm good. You?"
            v "Photography stuff here and there. All part of the job. But you on the phone last night-"
            v "You sounded like you had something urgent to talk about."
            v "Something about... Camille?"
            p "She works at the resort Vincent. I talk to her sometimes."
            v "Ah."
            p "She's a cute girl you know, just a little strange sometimes I feel."
            p "I wanted to ask you about your experiences and what's going on."
            v "Do you mean to say... you're hitting on Camille?"
            p "I was flirting a little bit... and it ended up that way."
            p "I guess I also want to check that you don't have anything going on with her anymore."
            v "No... not anymore."
            p "I didn't want to ask her, but I was curious what happened between you two. I feel like it's troubling her a little."
            v "Well..."
            p "Sorry to just spring this onto you."
            v "No, no. I had some sort of idea this would be where the conversation would go."
            v "There's not much to it. I mean, we started seeing each other and then I decided I didn't like her anymore."
            v "She found it hard to accept and so that's when I just had to make a break for it."
            p "A break?"
            v "Yeah, I broke it up with her the day I bumped into you at the mall."
            p "Damn man. That's tragic. I had no idea."
            v "How... is she doing anyway?"
            p "That's what I wanted to talk to you about."
            p "On the surface she's really shy, but there's something deeper there man, and I don't know what it is."
            v "Something deeper?"
            p "Yeah. Like, I feel like she's quite lonely and a bit too eager to jump into a relationship."
            p "Is that a red flag?"
            v "You care about red flags, [p]?"
            p "Touche."
            v "Well, did she come onto you?"
            p "A little, but she was drunk, I guess. So there's that."
            v "Sigh. Let me just say, she's different."
            p "Different how?"
            v "She's not your average girl."
            p "Does she have some sort of complex going on?"
            v "I don't know, maybe. Point is- look, I mean I don't feel like I should be telling you whether to go for her or not."
            p "Sure man, I get it, but I just want to figure out if she had some warning signs that made you break up with her."
            v "..."
            v "Well... she just wasn't for me man. I wouldn't do it myself if I were you, but of course, we already know that."
            p "Dammit man, what exactly turned you off? Tell me everything."
            v "Very well! Don't say I didn't warn you..."
            v "I'd say Camille is a person who's had a tough past. Probably due to her experiences, she is less trusting then normal. That's why on the surface she seems quite shy and doesn't really engage."
            v "But under the right cirumstance, she can't supress the feelings she had previously been punished for showing."
            p "..."
            p "That sounds not bad to me. What's the problem?"
            v "The problem is! The problem is!"
            v "..."
            v "I shouldn't say anymore."
            p "C'mon man."
            v "Go say hi to her, [p]. The best way is probably for you to find out about her through talking to her yourself."
            p "Sounds fair."
            p "Thanks for coming again. Let me thank you with a milkshake or something from the menu."
            v "That's fine, [p]. Don't worry about it. I have to get back to work."
            p "So soon?"
            v "Yeah."
            p "By the way, why did you choose to meet in this place?"
            v "I thought it'd be funny."
            v "You see, Camille loves coming to this place."
            v "Just thought I'd show you it so you have a place in mind for a future date."
            p "You're just two steps ahead."
            v "But I'm behind on schedule!"
            p "Hang on, isn't it dangerous for us to meet up here then? I mean, if she likes coming around so much."
            v "No way she'll be here. She should be working at the resort around this time."
            p "The resort only opens in the afternoon- it's the morning right now."
            v "Oh shit."
            ## Glances around
            v "Look, I wouldn't worry too much."
            ## Show Camille outside looking in.
            v "After all, what are the chances?"
            t "(Oh, why is [p] talking to Vincent?)"
            t "(Could they be talking about me?)"
            t "(No Camille, you musn't, you always assume the worst! It's... probably nothing!)"
            ## Show Camille leaving
            v "Alright, give me a call whenever you want to catch up again, huh?"
            p "Will do."
            $ camillelvl + 1
            jump map

        else:
            "I need to make sure I have the silver membership first."
            jump Camille
    if camille lvl == 4:
        play music "sounds/armoir.mp3" fadeout 1
        p "Hello Camille."
        t "Hello [p]."
        p "How are you feeling today?"
        t "I feel good, [p]. Sorry about last night!"
        p "Don't say that Camille, we all got a little drunk that night thats all."
        p "So you free after work sometime? We should go out again."
        t "You want to go out with me?"
        p "Of course, who wouldn't?"
        t "Aha-"
        t "..."
        t "Mmm!"
        p "Where should we go this time?"
        t "There's this place that's quite good. It serves ice creams and other desserts."
        t "It's called the Ice Cream Parlour. Have you... heard of it?"
        p "I... think I know the place you're talking about."
        t "Shall go there after work then?"
        p "Sure. In the meantime, can I chill somewhere in the resort?"
        t "Of course, where do you want to go?"
        p "I think I'll go to the bath house this time."
        p "I think I already have the membership for that."
        t "You do!"
        p "Sweet. I'll see you later!"
        ## transition to bath house
        "Time to splash around, relax and kill some time."
        "What'll happen if I doze off again?"
        "That girl from my dreams..."
        "Last time I was able to talk to her. But many times I passively listen. And can't respond."
        "That's the thing with dreams though. Sometimes you feel like you just can't move."
        "The next time I see her, I'll charge at her. If it's just a dream, nothing will happen."
        "But this time I need answers."
        "..."
        "I just need to fall asleep. Shouldn't be too hard, after all-"
        "zzz....."
        ## Wake up
        "Where... am I?"
        "Am I dreaming?"
        p "Hello?"
        p "Who are you?!"
        "It's her."
        p "Hey!!"
        p "Do you hear me!"
        "No answer."
        p "Don't wanna talk? I'll make you talk."
        p "!!!"
        p "I can't move!"
        x "I appear in your subconcious to guide you, [p]."
        x "This is not a show of strength. This is about the choices you make and how they affect the ending of your story."
        x "I can't give you more, not now. Some things you have to see to the end yourself."
        p "Guide me?"
        p "Why did you summon me here?"
        x "..."
        x "I didn't. It was you who brought me here."
        p "What?"
        x "You have some talent."
        x "This might end up working out."
        p "What will work?!"
        x "This won't happen again."
        x "Well done, [p]."
        p "Wait, wai-!"
        t "[p]?"
        p "Ah!"
        p "I fell asleep again."
        p "So sorry Camille, haha. This is getting old for me."
        t "It's good right? It means you're relaxed."
        p "Why don't you come jump in the pool with me here?"
        p "We've got time right?"
        t "Erm. I didn't bring my swimming gear, sorry!"
        p "Oh, alright."
        p "You got changed. Nice."
        t "Mm!"
        p "Shall we go?"
        ## Transition
        t "I like this place a lot. It's got really good dessert, and I just love sweet things."
        p "I like this style of decor."
        t "When was the last time you came?"
        p "I've been here once before."
        t "How long ago was that?"
        p "This morning actually."
        t "What was the occassion?"
        p "Hahaha. Asking a lot of questions, Camille."
        t "I was just curious."
        p "..."
        p "I came myself out of boredom, but got chatting with some friendly guy along the way."
        t "Did you see something on the menu you liked?"
        p "I didn't actually get to have anything, so I'm looking forward to this one."
        p "What do you suggest?"
        t "The waffles here are really nice - I really like them."
        p "Waffles? They do that in Ice Cream places? I was going to ask for a soft serve or something."
        t "They have dessert here - so there's actually pancakes too!"
        t "What do you want to try?"
        p "Erm. I'll have whatever you're having."
        t "Waffles then."
        wai "What would you guys like to have?"
        t "Two orders of waffles please!"
        wai "Good choice, just a moment."
        p "So, yeah."
        p "Busy day today?"
        t "The resort is becoming more popular and they're renovating things left and right."
        p "Well, that's cool I guess. There's actually quite a bit to do at the resort."
        p "You must be very skilled - you're holding down the fort by yourself!"
        t "I'm alright, haha."
        p "I'm playing."
        t "So [p], what's your story?"
        p "Me? I grew up here you know. I moved after I graduated from high school to study."
        p "Didn't work out too well though. Got caught up in the latest cryptocurrency craze and lost my money."
        p "And after all that I'm back here. Resting. A little insecure, but enjoying life and picking myself back up."
        p "Haha. Not very impressive, I know."
        t "Don't say that, [p]..."
        t "I- I know what that's like. Sort of, losing your way, and not feeling comfortable with where you are."
        p "There, there. A kindred spirit. So what's your story?"
        t "..."
        wai "Two waffles, as ordered."
        t "Ah, [p], you have to tell me if you like this."
        p "It looks damn good!"
        p "All of a sudden, I'm really hungry."
        p "Shall we?"
        t "Let's!"
        ## A few moments later...
        p "There's a bit of ice cream on the waffle. It's great. How did I not try this before?"
        t "Ah, there's always a first for everything."
        p "We were talking about something before the food arrived, but I don't remember what it was."
        p "What were we talking about again?"
        t "Mmm, I don't remember."
        p "..."
        "Vincent said he didn't like Camille because of something about how she suppresses her feelings, is not as trusting and is shy to start with. Something to do with her past experiences."
        "But isn't this how you want girls to be?"
        p "You know, I want to come clean."
        p "..."
        p "The person I talked to this morning was Vincent."
        t "..!"
        p "I understand you knew each other before."
        p "He's told me everything."
        t "..."
        p "And you know what? I don't mind one bit. Everyone's got their own quirks and what not. I mean, it's who you are Camille."
        p "I think you're a very cute and beautiful girl through and through, and you can be honest with me."
        t "Y-you don't mind?"
        p "I don't. I probably can't imagine what happened in the past, but you don't have to hide it."
        p "I won't judge."
        t "I've been wanting to hear that for so long..."
        p "Haha, you alright there?"
        t "Ah, please come back to my place, there's a lot I want to show and tell you."
        p "I'm there."
        "I wonder what happened to her in the past."
        "Looks like I'll learn a lot tonight."
        ## Transition
        t "Welcome again, [p]."
        p "Glad to be back."
        t "..."
        p "Is there something you wanted to let me know?"
        t "Do you... like me?"
        p "I think I do, Camille."
        t "Thank you, [p]."
        t "I... want to show you something. Please close your eyes."
        p "Camille?"
        t "I'll let you know when you can open them."
        p "Very well."
        "..."
        "Oh my god what's this going to be?"
        "A kiss?"
        "A blow job like last time?"
        "Is she stripping?"
        "I wonder...."
        menu:
            "Sneak a peek.":
                $ depravity += 1
                "Wow, she {i}is/{is} stripping."
                "I've never seen Camille wear anything racy or provocative."
                "She's always been modestly dressed, This is the first time I'm seeing her... like this."
                "I don't think many people have seen her like this at all - I should count myself lucky."
            "Wait.":
                "She deserves this bit of respsect."
        t "[p]?"
        p "Camille."
        t "You can open your eyes now."

    ## generic
    scene cam-5
    p "Working hard Camille?"
    t "I always try my best."
    jump Camille
