label ball1:
    # lots of images about them getting ready
    # arrives at restaurant
    "Why is it always that I am the first one to arrive at these places?"
    "Why can't they be first for a change?"
    "Are they taking longer because they're spending extra time to get dressed?"
    "In that case... I'm geting excited."
    "It will sure to be a feast for the eyes."
    "{i}Ring.... Ring.... Ring... {/i}"
    "Hmm, someone's calling my phone."
    p "Hello, [p] here."
    n "It's me, your favourite girl."
    p "Ooh, Sandy?"
    n "You're such a clown."
    p "Just kidding, what's up Nicole? You guys here yet?"
    n "No, just calling to let you know that we hit a snag."
    p "A snag?"
    n "Your [mr] and I both know how to do our looks, but Kaira's never been to a ball or formal before."
    n "We're just sorting out her look."
    p "Oh really? How long do you think that's going to take?"
    n "It won't take too long."
    p "Somehow I really doubt that."
    n "Grumble grumble, [p]. We're hurrying up already, I promise."
    n "But hey, that will make the reveal that much sweeter, right?"
    p "Haha, looking forward to it, babe."
    # ring ring, they appear
    p "Wow..."
    # panning shot
    p "You guys look... different."
    p "It's good, I like it!"
    p "I love your look, [mr]! It's sophisticated and it looks so seductive at the same time."
    p "I see you've dyed your hair another colour, Nicole!"
    p "Like a high class-"
    n "Ahem?"
    p "Princess. Like a princess!"
    n "I'll take that."
    s "Hehe, hi [p]."
    p "Wow, Kaira, just wow."
    "She was no longer a young girl. In front of me was a woman."
    p "You look so grown up. You're a real woman, you know that?"
    s "Haha, I'm still not used to this look."
    n "Doesn't it make you feel confident, Kaira?"
    s "I guess it does."
    m "Don't be shy, Kaira. Your [mr]'s a model you know."
    m "I know you have some model material inside you too!"
    m "Look how mature my girl looks!"
    s "Ahah, thanks [mr]."
    s "Do you like it, [p]?"
    p "i love it, Kaira, I really do."
    p "I love all of you!"
    p "Let's grab a table shall we?"
    # Transition
    n "Kaira did her make up all by herself!"
    n "Mostly."
    m "Did she now?"
    s "Mmm!"
    p "Kaira doesn't need make up to look good, isn't that right, Kaira?"
    s "Hehe~"
    s "But it's so much work! Maybe I'll save this look for special occassions."
    n "And tonight is a special occassion, is it?"
    p "Of course!"
    p "What, we got nice food, good venue, good company..."
    p "Gorgeous ladies, of course! that goes without saying."
    m "Well let's see if the gentleman measures up."
    p "I'm sure he will, after all, I hate to disappoint."
    # music plays
    m "Such regal music~"
    m "Have you ever danced, before, [p]?"
    p "I have."
    m "Have you now?"
    p "Yeah, of course, at discos, clubs."
    m "That's not real dancing, [p]. Come on, let me show you the real deal."
    m "Come dance with your [mr]."
    p "Umm!"
    p "You sure about this?"
    m "Keeping a lady waiting? Is this the kind of gentleman you are?"
    p "No, of course not. Let's go!"
    # dance
    "Amanda secured her hand on shoulder, and clasped her other hand onto mine."
    "Her touch was gentle but firm, and I was taken along for the ride."
    m "A bit slow, but you have potential, [p]."
    p "You're experienced at this, [mr]. I'm just a baginner."
    m "I dare say I'm a bit more experienced in many things, [p]."
    m "I could teach you how to dance."
    p "You could teach me many things, I'm sure."
    p "What can you teach me?"
    m "Well that depends. Do you like to do it fast, or slow?"
    p "Are we still talking about dancing?"
    m "Of course."
    m "Your mind is in the gutter, isn't it?"
    p "Your dress isn't helping much in that regard."
    m "A man has to control his urges."
    p "just as you control yours."
    m "Exactly."
    p "Whoa-!"
    "Amanda spun me around, and I slipped before regaining my footing."
    m "Thank you for the dance, [p]."
    p "Anytime, [mr]."
    # back to table
    n "Very well done, Amanda, [p]."
    s "Yeah, [mr]! You have to teach me how to do that one day too!"
    m "I promise I will, Kaira."
    s "Can you teach me now?"
    m "I just danced, and leading [p] is no easy task!"
    m "I'll take a break first."
    n "While you were gone, [p], I requested a song."
    p "A song?"
    n "What, I want to dance too."
    n "It would be a wasted opportunity to not dance with my boyfriend at such a formal location."
    m "No breaks for you tonight, [p]."
    p "No worries. I gotta train my stamina anyway."
    n "Oh please~"
    # music changes
    n "My song's up."
    p "It's oddly wholesome."
    n "I can be a good girl too."
    n "Come on, up!"
    p "Groan, groan..."
    # Transition
    n "Let's put on a good show, shall we?"
    p "Might as well be."
    n "Everyone's looking at us, right?"
    p "Everyone's looking at {i}you{/i}."
    n "Am I that attractive?"
    p "With platinum hair that shiny, people are wondering what's shining in their eyes."
    n "Haha!"
    n "Come on now, show me what you've learnt."
    "I held Nicole around her lower back, and could feel her toned and tight body underneath her dress."
    p "You go to the gym, girl?"
    n "I look after myself. You appreciate it, don't you?"
    p "I'm a lucky guy."
    # dance
    n "Both of us grew up in and around the club culture."
    n "This stuff is too high class for me."
    p "We could always learn, right?"
    p "Beats twerking at some dingy club."
    n "If you say so~"
    "We danced around a bit more, and with Nicole, it's more sensual."
    "Our hands slipped around, groping each other, and we shared a few giggles."
    n "This is really getting me in the mood."
    p "You free tonight?"
    n "Of course. But we're in different rooms, aren't we?"
    p "We could always go somewhere. It's not like they don't know we fuck."
    n "That's true."
    n "So how shall we end this? A twirl like with your [mr]?"
    p "Up to you, haha."
    n "In that case...."
    "Nicole pulled me up close to her, causing me to lose my footing."
    "And pressed her lips against mine."
    p "...mmm!"
    n "Well, all the boys watching me now know I'm taken for sure."
    p "How'd they figure?"
    n "The kiss?"
    p "They might have missed it. We really need to be sure."
    n "Sure~?"
    p "Sure that you're my woman, not anyone else's."
    # Kiss
    p "Good."
    p "Woo, I need to sit back down and cool down a bit."
    n "That was spicy, wasn't it!"
    # back to table
    p "So, did we miss much?"
    m "Not too much!"
    m "But, Kaira's getting a bit of attention from the boys on the other table."
    s "Ah, [mr]!"
    "Kaira looks down, as if unwilling to meet the eyes of the table nearby."
    m "Don't be shy, Kaira! Enjoy it! Isn't it time you got a boyfriend, anyway?"
    m "If you meet his gaze, he might come talk to you!"
    s "Why would he talk to me? He'll probably talk to you or Nicole first..."
    n "Not me. Everyone in the room knows I'm with [p]."
    m "You're the first one they'll look at, Kaira."
    s "Ehh..."
    n "How does that sound, [p]?"
    n "Your [sr] might finally find a partner just like you with me!"
    n "She'll finally be able to experience what we're experiencing together, and she won't be missing out anymore."
    p "Man, really?"
    n "Aren't you happy?"
    p "..."
    menu:
        "I'm not too keen.":
            $ depravity += 1
            p "We don't even know that guy."
            p "Creepy boys aren't cool."
            n "Aww, [p] is feeling protective."
            m "What do you think, Kaira?"
        "What does Kaira think?":
            s "Ah..."
    s "I don't know... I'm a little shy..."
    s "What usually happens? I-Is he just going to come up to me?"
    s "What do I have to do afterwards... oh god!"
    m "You don't have to do anything you don't want to."
    m "Go on, just meet his gaze."
    m "This is all a learning experience!"
    p "..."
    s "Oh... okay, if you think so, [mr]."
    # Kaira looks up
    s "Eek! He's coming over."
    n "Just act natural."
    douche "Greetings milady~"
    douche "I glimpsed through yonder side, only to witness a damsel in seeming distress~!"
    douche "Are you beset by an ailment, mayhaps~?"
    douche "Doth thee hath an ailment, that thine fine gentleperson may remedy~?"
    "What a douchebag!"
    s "Um - Sorry! I don't quite understand!"
    s "M-My name's Kaira.. and yours?"
    douche "Thine utterance is like an angel singing praise to my lowly ears~!"
    douche "I have nought name milady, yet I must confess to thee~"
    douche "At present, I am euphoric~!"
    douche "Not by mine intelligence, but by thou fairest beauty~"
    s "Ah..."
    douche "Alas! I see thou hath been surrounded by company~!"
    douche "I will grant you pause to consider, for I believe I have placed my best foot forth, awaiting your appraisal~"
    # disappears
    s "What... did he want?"
    m "I'm not sure, what a strange man!"
    n "He said he's waiting for you to appraise him, or something. Maybe he wants you consider approaching him later?"
    s "Eh.. I think I won't..."
    p "Creepy fucker, right?"
    m "Language!"
    p "Sorry, [mr], couldn't help myself."
    m "Though in this case, I could almost excuse you. That was very strange indeed."
    s "Urgh, that was so creepy!"
    s "Why can't guys be more normal like [p]?"
    s "They always treat me so weird."
    n "It's called the pretty girl problem, Kaira. Not such a problem sometimes, though!"
    s "Eh... I'm not a fan, Nicole! It must be this outfit and the make-up making it worse."
    m "While we're still waiting for food, why don't you give her a dance, [p]?"
    m "Give Kaira the full experience!"
    p "Hmm, sure."
    p "Kaira?"
    s "Oh, yes, it'll be so fun!"
    s "And also to forget about that guy... hehe..."
    # start dance
    "Kaira was softer than Nicole. Her back had a soft layer, and wasn't as toned as Nicole's."
    "This made her more precious, in a way. More vulnerable."
    s "[p]..."
    p "Hmm?"
    s "Why are people staring?"
    s "Do I look weird?"
    p "They're staring because you're beautiful, Kaira."
    s "..."
    p "Look up, Kaira, be confident."
    p "It's just me and you now. Shut everyone else out."
    s "I see..."
    # looks up
    "We spun around the floor, arms around each other."
    "Awkward, tentative."
    "Over time, our pace slowed and we slow-danced."
    "Her head resting on my chest."
    "Both oblivious to anything aside from each other."
    "How long was it?"
    "Were people still looking?"
    douche "Hey!"
    douche "HEY!"
    douche "Cara! Why are you dancing with him?"
    douche "Didn't you see him dance with another slutty looking girl just now?"
    douche "He's a bad guy, why do girls like you trust him?!"
    s "Huh? I-I..."
    s "[p] is just my-!"
    douche "All you sluts are the same. I thought you were different, I really did!"
    douche "Fucking sluts like you always suck up to douchebags."
    douche "Why don't you give a nice guy like me a chance?!"
    douche "This is your last chance! Are you going to go with him or me!"
    s "..."
    douche "Fine!"
    douche "You know, I bet you're really fucking ugly under all that make-up."
    douche "You're so ugly you dress like a slut and thinks it makes you hot."
    s "!!"
    douche "Fucking disgusting!"
    douche "Fucking whore! Why don't you go suck his dick now?"
    douche "You'll fucking do it. I bet you would."
    s "Why are you-?"
    s "I..."
    # sobs and runs Off
    p "What the hell man?"
    p "And you could speak normal the whole time?"
    douche "Sluts, am I right?"
    p "What the hell man?"
    douche "Tell me, how do you do it? How many have you got? Two? Three?"
    p "Fuck off."
    douche "Whatever man. You're just jealous. I'll go find myself a proper lady."
    p "..."
    # Transition
    s "I... wanna get this make-up off."
    m "Don't let what he said bother you, Kaira!"
    m "That was a very nasty person, don't take it to heart."
    s "I feel so gross and disgusting. This... isn't me..."
    p "I'm so sorry I couldn't stop him earlier."
    s "I-I want to go home..."
    p "Ignore that guy, Kaira."
    p "He has no idea what he's talking about."
    s "T-this make-up isn't for me, I-"
    douche "Ba! HAHAHAHA!"
    douche "Look at her bro! Crying crocodile tears! Damn they're manipulative."
    douche "Don't say I didn't warn you, sucka!"
    p "Hey, that's enough, shut it."
    douche "Don't hate the player, hate the game."
    douche "I'm just telling the truth! That Cara slut over there is a vain little slut who has no other qualities than looking pretty."
    douche "I'm telling you, the larger the tits, the dumber they are!"
    # kaira sinks her head down
    p "You-!"
    douche "Whoa! Whoa!"
    menu:
        "Give him a beat down.":
            $ depravity += 1
            p "Hey."
            douche "Huh?"
            p "Nice suit."
            douche "Thanks, I-"
            # WHAM
            p "Sorry buddy, you gave me no choice."
        "Threaten him with a beat down.":
            p "You're not welcome here."
            p "You need to leave. I'm not asking twice."
            douche "Yeah, so what?"
            p "Leave."
            douche "Whatever. I'm out of here."
            douche "Only sluts and white knights here."
            "Jesus. I'm glad he's gone."
    p "That got me a little angry, sorry."
    p "Where's Kaira?"
    m "..."
    m "She took off, [p]. She said she just wanted some time to herself in the hotel."
    p "Sigh. All this, and the food hasn't even come yet. What a disaster of a night."
    m "She's not used to this treatment, but unfortunately, guys like that show up sometimes."
    n "Need to give them a good kick in the groin when they show up. Poor Kaira."
    m "Why don't you go accompany your [sr], [p]?"
    m "I feel bad for encouraging her in the first place. You were the only one who didn't."
    n "We'll take care of things here, [p]."
    p "You guys... thanks."
    p "I'll head off."
    # Transition
    p "K-Kaira?"
    s "{i}Sob, sob{/i}"
    "Kaira..."
    p "How are you going?"
    s "[p]... why are people so... mean?"
    s "People at school make fun of me..."
    s "And-!"
    s "Even now..."
    s "They say I'm just a dumb girl with big boobs..."
    p "Argh, don't listen to them!"
    p "You are a kind, loving, and insightful person, Kaira!"
    p "Trust me, it's true."
    s "..."
    s "But what if he was right, [p]?"
    s "..."
    s "What if really... nobody likes me."
    s "What if I'm... just like a toy to people."
    s "Just to look good for a while. But really, deep down..."
    p "Nonsense."
    p "I won't have you talk like that, Kaira. You know it's not true."
    p "Do you know how much people love you? How much I-"
    p "..."
    p "Do you know how much we all love you?"
    s "I know, I know..."
    s "Maybe... I need to care less about what others think."
    p "They don't know you like we do, Kaira."
    p "A lot the times, they're jealous too."
    p "..."
    p "I've been in a rut recently as you know. I came back and I didn't have any friends."
    p "I just had you guys."
    p "But I loved it Kaira. And I slowly made friends."
    p "I-I met Caroline just the other day!"
    p "You should meet her! T-There are so many good people in this world."
    s "Thank you [p], for understanding. And..."
    s "Thank you, for standing up for me."
    s "I think..."
    s "Even if nobody else likes me..."
    s "As long as I've got you, I would feel so happy."
    s "I feel lucky aleady, you know."
    p "I feel the same about you, Kaira."
    s "Hehe."
    s "At the restaurant, [mr] wanted me to get a boyfriend."
    s "Can't you do that for me though? [p]?"
    p "Well, Nicole's got dibs."
    s "She's not here right now though."
    s "..."
    s "Can I have another kiss?"
    p "Sure."
    # kiss - nicole enters?
    s "When you said you thought of me back at the beach..."
    s "I'm still not sure what you meant by that."
    p "What do you mean?"
    s "Like..."
    s "When you... find me attractive..."
    s "What do you mean... by that."
    s "..."
    s "Am I... just your [sr]?"
    s "Or am I..."
    s "Could I be..."
    s "Something... more?"
    "Kaira nuzzled up against me."
    "She was vulnerable, afraid."
    "But I am her comfort. And I know she's unsure."
    "I am unsure too. Feelings to protect contend with feelings to ravage her."
    "I am the duality of humankind."
    "I am the depraved soul and I am the saint."
    p "What do you want to know, Kaira?"
    s "I want to learn about... love."
    p "Is that what you want to know?"
    p "Love is... physical and... emotional."
    s "Mmm..."
    p "Do you want me to show you?"
    # Kaira's eyes widen
    # 360 view shot, Kaira considers
    n "Sorry to interrupt~"
    p "Nicole!"
    s "Nicole! What are you doing here?!"
    n "I sleep in this room, you know."
    n "What were you guys up to?"
    p "Just giving dear Kaira a cuddle."
    n "The Kaira I know is brave. You're resilient Kaira!"
    n "I tell you all the time, right? Let's just do our own thing, and fuck the haters."
    s "Ahaha! Yes, Nicole, I get it."
    s "I'm done feeling sorry for myself. I'm happy that I've got you guys in my life."
    s "[p] helped me understand that."
    n "You alright yourself, [p]?"
    p "Yeah. I'm fine. You just got back?"
    n "Yup."
    p "Where's my [mr]?"
    n "She's in her room. She wants to see Kaira later, though."
    n "She didn't want to crowd the place up."
    n "Aww, Kaira. Gimme a hug."
    p "..."
    s "Thanks, [p], Nicole."
    s "I think I'll go see [mr] now, and I'll stay the night with her."
    s "Do you want to swap, [p]?"
    p "Good idea, that's for the best."
    s "Don't be too sad without me, [p]!"
    s "I'll see you real soon!"
    s "Goodnight guys."
    # Kaira goes
    n "Horrible, what happened tonight."
    n "Kaira's still too innocent."
    p "I'm glad that's all over. But hey."
    p "We get some 'us' time now."
    p "Come on. Tell me."
    p "You came in at the perfect time."
    n "Really~?"
    n "What were you going to do?"
    p "We were going to have some bonding time."
    n "What is that? Bonding time?"
    p "I don't know. Whatever it was, you came in just at the right time."
    p "Why?"
    n "Alright, I interrupted a bit. I'm sorry."
    n "I still don't know why you won't just say I got in the way of you fucking your [sr]."
    p "That's not what was happening."
    n "..."
    p "Not necessarily."
    p "But, even if what you're saying is right, why would you interrupt it. Wasn't that what you wanted?"
    n "I want fun, [p]. I just wanted to be a part of it!"
    n "I'm not that complicated, really."
    p "You just want to be a part of the fun?"
    n "Yeah!"
    n "Think about it. I've been nuzzling up to Kaira for so long. I want to be there when we despoil her~!"
    p "Jesus."
    n "What~? I stopped you from venting your tensions?"
    n "You could always take it out on me, you know?"
    n "Have you ever fucked a blonde before?"
    p "Well... actually..."
    n "A {i}platinum{/i} blonde?"
    p "Well now that you put it that way..."
    p "You definitely deserved to be punished."
    n "{i}Rawr...{/i}"
    n "Let's spend this night all to ourselves~"
    # sex
    # next scene flash black to past scenes
    x "When the world comes crashing down upon you, what will you do?"
    p "AHHH!"
    n "[p]?"
    p "I had a nightmare, I guess."
    n "After last night, all you should be having are sweet dreams."
    p "Waking up next to you does a man crazy, you know that right?"
    n "I'm sexy?"
    p "You're the whole package."
    p "Nicole, you must get cat called all the time."
    p "How do you deal with it?"
    n "I wasn't just born like this, you know."
    n "Part of it is natural, and part of it is hard work."
    n "And a little bit of initiative of course."
    p "Initiative?"
    n "The breast enhancements."
    p "Ah."
    n "I love how full they look. How full and firm they are."
    n "Don't you?"
    p "Of course. They're a real head turner."
    n "Anyway, what was your dream about?"
    p "I don't know. I'm not sure."
    p "..."
    p "But there's always a common theme."
    n "Tell me babe."
    p "There's this girl, woman - I don't know."
    p "It's like.. she's always watching what I'm doing."
    p "Is she my concience?"
    n "..."
    p "She's got this hair that actually looks like yours."
    p "Your silver colour right now, anyway."
    n "That's strange."
    p "Heh, I know right?"
    n "Probably nothing to worry about."
    p "I know, I know. Just a dream."
    # Nicole turns over and smiles to herself
    # END
