label hotel1:
    m "Why don't you give us a tour, [p]?"
    p "All I know is that we got two rooms."
    p "I don't know, let's take a look at the first one."
    s "Oooh, [p]! This is so fancy!"
    s "I don't think I've ever been in a hotel room so fancy before."
    n "Wow, it really does have a big size."
    p "That's what she said."
    s "What do you think, [mr]? This is cool right?"
    m "Of course, Kaira of course."
    s "I want this room! Who wants to stay here with me?"
    n "I will, Kaira."
    p "You're not gonna come with me instead? What?"
    n "We spend tons of time together already, [p]. It's girls night tonight."
    s "Oh yes Nicole, yes!"
    s "Sorry [p]! Ooh!"
    m "Looks like you'll be with me tonight, [p]. I hope you're not too shy about sleeping with your [mr]!"
    p "..."
    p "No, its fine, it's fine. You guys enjoy."
    p "Come on, [mr], let's go check out our room."
    ## transition
    p "Oh yeah, just the two of us now."
    m "Finally some peace and quiet, huh?"
    p "I love those two, but it's good to get a break from it all."
    m "Every man needs a break once in a while."
    p "That's right [mr]. I'm glad how this has worked out actually."
    m "Things seem to {i}have{/i} worked out for you, haven't they?"
    p "Yeah, you mean with the plane trip beign quite nice, and the hotel rooms being decent also."
    m "Speaking of hotel rooms, I like this one too. What a large room just for the restroom."
    m "At least there's a curtain here. Otherwise, it would be quite promiscous, don't you think?"
    p "Yeah."
    m "So, how are you getting along with Nicole?"
    p "We're alright."
    m "She's definitely not shy around you at all."
    p "She's like that. A bit sex hungry and loves to tease and have fun."
    m "I got that impression on the plane. Did you know she was eyeing me as she flashed you her breasts?"
    p "Oh, hahahha. You saw that..."
    m "What do you think she's trying to do? Is she trying to make me jealous?"
    p "Gee, I don't know. She's like this around Kaira too. But I think deep down there's some good in her."
    m "You know what I think it is?"
    m "She's challenging me."
    p "No way, she knows that you're my-"
    "Oh wait... Nicole teases me about Kaira too, she doesn't give a damn about boundaries."
    p "Actually, it's possible."
    m "Am I weaker in comparison? Am I... a failed woman?"
    m "Am I not... attractive?"
    p "Of course you are, [mr], we've done this already."
    p "You remember? It's just you who always goes back on it and putting me back on edge."
    m "I've... never thought about it like this before."
    m "(All this time, I thought I was in the wrong, and that you had all the power...)"
    m "Yes..."
    m "Boundaries."
    m "I..."
    "It's what I tried the aphrodisiac."
    "I wondered if it would help me crack through."
    "But now I'm thinking, maybe the aphrodisiac was us all along. Is that right, [mr]."
    m "(Sometimes, all people need is an excuse to do things. Something they can blame it on.)"
    m "What time do we get up tomorrow?"
    p "Early morning. Kaira wants to go to the beach or something. We'll need to grab the van then drive over."
    m "Best we get some shut-eye then, hmm?"
    p "Right. Um, go get ready. I'll just let the girls know the plan then I'll be back."
    m "Okay [p], see you soon."
    # Transition
    p "Hey girls, what's up?"
    n "{i}Giggle{/i}"
    s "OMG I can't believe you said that."
    n "I know right, they never saw it coming!"
    p "Uh, girls? It's nice to know that you guys are having fun."
    s "[p]! We're having some girl on girl time, what's up!"
    p "Early day tomorrow guys, we have to pick up a van. So get to bed soonish okay?"
    s "Okay!"
    p "..."
    n "Yes [p]? What are you hanging around for?"
    p "What, just thought I'd give you some company!"
    n "It's girl on girl time, [p], not boy on girl on girl time."
    n "You'll have to wait another time for that."
    s "We're just doing our girl gossip, [p], just go hang out with [mr] instead!"
    p "You're kicking me out!"
    n "We'll suck you off tomorrow to make it up."
    s "Hey! ... I didn't say that I was {i}definitely{/i} going to do it..."
    s "I was kind of, um. joking..."
    p "Huh?"
    n "Scoot, [p] and goodnight! We'll see you tomorrow."
    p "Early morning!"
    n "Early morning!"
    # transition
    p "Sorry, [mr], I'm back."
    p "..."
    p "Asleep already."
    "Oh, [mr], you're so beautiful. You don't need to worry about anything at all."
    "We're both new to this. Both of us don't know how it will work out."
    "I just hope you feel the same about me as I feel about you."
    "I hope one day we both know it about each other, and then we can stop pretending."
    # sleep
