label hol_plane:
    p "Welcome. Here we are, I guess."
    m "You guess?! [p]!"
    n "Wow, you weren't lying."
    p "Why would I lie? What do you think, Kaira?"
    s "..."
    s "Ah..."
    s "This. Is. So. Awesome!!"
    s "Can we just go in?"
    p "Oh yeah it's all good. I didn't pay for service though."
    p "This whole thing is AI powered. It'll take us there, but we'll have to serve ourselves."
    m "That's good. Some bit of privacy-"
    n "..."
    m "-is always something I like to enjoy."
    s "Well, in that case, it works out, doesn't it [mr]?"
    s "I'm going to go explore!"
    m "Off you go, Kaira."
    m "Look how happy you've made her, [p]. I'm very glad to see it."
    m "You know, she's been a lot happier since you've come back."
    p "Really? I imagine she's always had this sort of happy-go-lucky."
    n "You're selling yourself short, [p]. This jet is really nice."
    n "It's so classy. I can still barely believe it."
    n "You're the guy that has my second-hand iDante phone."
    p "I'll look forward to you making it up to me."
    n "Haha! I might just follow Kaira and take a look around."
    p "We can take a good look around later, but we're taking off soon. Make yourselves comfortable and get seated for take-off."
    m "Is there a bathroom at the back? I might excuse myself before we go."
    p "Oh yeah sure, just around the back."
    m "I'll be right back."
    ## Nicole talk then rest are seated
    n "These chairs feel nice."
    p "I'd hope so. This ride wasn't cheap."
    n "Is that how you do things, [p]?"
    n "Spend money on expensive things to win women over?"
    p "Oh I think I put in a bit more effort than just that!"
    p "But you're impressed, aren't you?"
    n "I'm not a gold digger, but I do appreciate the effort."
    n "I trust that the rest of the trip will maintain the same high level of standard?"
    p "Haha, bitch."
    n "Hey!"
    p "It's the people that make the trip enjoyable, you know. It's the company."
    p "And I think we've got mighty fine company here."
    n "But a first class jet experience wouldn't hurt right?"
    p "I'm liking it! It's a first for me."
    n "What do you have here?"
    p "Some drinks, some food. The bed is pretty comfortable too, but we might not even need to sleep."
    n "Oh actually, we might need to sleep."
    p "Really? The flight won't take too long, we should be there by night-"
    n "We'll be using the bed."
    p "Oh."
    n "Yes. {i}Oh{/i}."
    p "Whatever the case. it'll have to wait, we're taking off soon."
    n "This AI system is going to take off?"
    p "Yeah. Something like that. I didn't really read the manual."
    p "When you pay that much money, you just expect it to work."
    n "Oh, so should I grab Kaira now?"
    p "Let's call em' back."
    n "KAIRA!"
    p "Um, [mr]!"
    # Characters back
    s "Wow, that bed is really nice, [p]!"
    s "It'll be a waste if we don't get to use it later."
    n "It would be."
    p "What did you think about the back?"
    s "I love it. It's so fancy."
    p "We can take a longer look later. But for now, let's get seated. We're about to take off!"
    m "Someone called?"
    p "Yes, [mr], it's time to go soon!"
    m "Please get seated!"
    m "Wow, these are some nice chairs."
    p "I knew you like leather."
    ## Plane starts
    play music "sounds/effects/cabin.mp3" fadeout 1
    s "Wow! Is the plane starting to take off now?"
    p "Should be, yeah."
    n "I wonder if we're going to get any notification."
    p "Yeah I don't know, I didn't read the manual!"
    m "Hmm..."
    play sound "sounds/effects/captain.mp3"
    $ renpy.pause(13.0,hard=True)
    p "Wow, there's even a virtual pilot?"
    n "You paid for it, not me."
    p "This {i}is{/i} luxurious."
    p "It's started going up!"
    s "Oh this feels funny. Kind of like I'm pressed to my seat."
    s "How long until I can get up again?"
    p "I think after it starts climbing... a few moments after that."
    m "There should be a sound that plays, until then, be a good girl, Kaira!"
    n "I imagine you've flown quite a bit, Amanda."
    n "As a model, you must have."
    m "Oh, I've flown once or twice!"
    n "My sister's a model, did you know? Her name's Saffron."
    m "Ah yes, I saw her at the modelling show before."
    n "I think she's quite popular. Were you watching?"
    m "I was one of the models at that show, actually."
    n "Oh, I'm so glad to hear that my sister is maybe even on the same level as you!"
    m "Ah, stop flattering me!"
    m "You share a striking resemblance of your sister."
    n "Yes, everyone says that. But my goal one day is for people to say that Saffron is a striking resemblance of {i}me{/i}."
    m "Oh yes, comparison is a thief of joy. I would know."
    n "It really is."
    play sound "sounds/effects/beep.mp3"
    $ renpy.pause()
    s "That might be it?"
    p "We've definitely levelled off."
    s "Good! I'm going to take a look here."
    s "There's so much space up at the front too!"
    s "Ooh, the cockpit."
    p "Maybe we shouldn't go in there."
    s "Please, let me! I pwomise I won't touch anything!"
    p "How can I say no to you, Kaira? Fine."
    s "You come in too!"
    p "Kaira?"
    s "I just want to see what it feels like. Here, you be my copilot!"
    p "I have no idea how to fly this thing, Kaira, and neither do you."
    s "It's just for a moment!"
    p "Sigh."
    s "Wow, we're up so high I can't even see anything down there!"
    s "We'd be super dead if we were to go down now..."
    p "Don't remind me."
    s "Hmm, what does this button do, I wonder..."
    p "Don't!!"
    s "Just kidding, [p]! You're so funny sometimes."
    s "I'll go back now, and you can finally relax."
    p "Phew."
    s "It's such a waste to not have this whole plane filled up."
    p "Hmm?"
    s "There's just so much space! I can sit here, here, here or there. I can't make up my mind."
    s "Look, what a huge... couch?"
    p "This is luxury, my little Kaira, mwa hahaha."
    p "But... I hope you don't get too used to it."
    s "I just wanna... lie down right here!"
    s "And maybe watch from the cockpit a little bit later..."
    p "Is it wise for me to leave you unsupervised?"
    s "You can trust me!"
    p "..."
    s "If I get in trouble, I'll yell!"
    p "Alright, have fun."
    s "I love you, [p]!"
    p "Love you too Kaira."
    s "No but {i}really{/i}."
    p "Right back at ya."
    # Amanda middle cabin
    p "Whats up. [mr]?"
    m "I'm just taking a look at the drinks we've got here!"
    m "We even have some Dante's Original."
    n "Oh [p] loves that stuff."
    m "Are you a big social drinker, [p]?"
    p "Oh no. I only drink in private."
    n "Bahaha."
    n "What are our entertainment options, [p]?"
    p "There's no in-flight entertainment?"
    n "I'm sure there is, but this is a luxury experience right? What else is there?"
    p "Aside from the foods and drinks?"
    n "Well I never intend to sound ungrateful, but I can smell the possibilities."
    p "Sorry to be cheeky, haha. Actually there is a very advanced entertainment system."
    p "This TV is mostly for show. The real deal is apparently a live projection thing hologram thingy."
    m "A holographic show?"
    p "Yeah. Like I said before, I don't really study manuals but I did come across it, I think."
    p "Apparently it has an entertainment that is tuned in with the customer."
    p "It's all artifical inteligence mumbo jumbo to me, but this is might be interesting. Let's give it a go."
    m "And this will show your deepest darkest desires? Fufufu~"
    n "It makes me curious what we would see for your case, Amanda!"
    m "(What is it that I deeply desire?)"
    m "(Don't tell me Nicole is teasing me about [p]...)"
    m "(She must have seen my look back then!)"
    m "I think all you would see is a warm scented bath!"
    n "With just yourself, and with a special someone?"
    n "I do apologise! I can act too familiar sometimes."
    m "Not to worry at all."
    p "Okay let's flick this thing off. I mean, on."
    "..."
    # Milos
    n "..."
    m "..."
    p "..."
    m "He... looks so life-like."
    n "Ahaha! Is this really your fantasy, [p]?"
    "What the fuck?"
    p "It-it's Milos!"
    m "Who?"
    n "Not to worry, [p]! He's everybody's fantasy."
    m "Some kind of stripper?"
    m "[p], what kind of things have you been watching?"
    p "There must be some kind of mistake."
    n "He's coming towards you!"
    n "The flick, look at the flick, hahaha!"
    p "Ricardo, can you hear me?"
    p "..."
    p "It's just a projection."
    m "Um, can we turn this off?"
    p "Huh?"
    p "Oh right. Sorry Ricardo, we have to go. I'm sorry!"
    m "That was just a video, [p]. That wasn't the real guy."
    p "Oh shit. You're right. It was a like a spell was over me."
    n "They say he can turn straight males gay."
    n "Amanda saved you from the spell!"
    p "Whoa that was intense. It was like he was really there."
    m "Why don't you take a rest, [p]? You... look like you need it."
    p "Yeah, I'll uh, retire a bit."
    # Leaves
    m "Boys, am I right?"
    n "Tell me about it. But he's fun to have around isn't he?"
    m "Let's have a toast to that. Want something to drink?"
    n "Sure, why not!"
    # Switch to MC
    "Whoa, the Milos meme is real."
    "Let me empty that out right here..."
    "Oh that feels nice."
    "I feel cleaner already."
    "There is even a shower here. I would feel bad if I didn't get to use everything before the plane lands."
    "Just feels like a bit of a waste."
    ## Back to Nicole
    n "[p]'s taking a while. I might just go check up on him."
    m "Huh? Oh, sure. I'll just be here."
    n "Hmm, [p]?"
    n "Are you alright in there?"
    p "I was just taking a piss."
    n "I wondered if you needed help, so I came by."
    p "What were you going to help me with? Were you gonna hold my dick while I pissed?"
    n "Christ, I just wanted to check up on you. Unless you really want me to hold your dick?"
    p "What's the real reason you came in, huh?"
    n "What, can't I just say hi?"
    p "I'm doing good, that projection stuff just got be a bit dizzy. After a splash of water on my face, I feel much better."
    n "You're not nauseous at all? Not going to throw up?"
    p "Nope."
    n "Well on the safe side, I think you should just lie down on the bed for a bit."
    p "I don't really-"
    n "Come on, come on!"
    p "..."
    # migrate
    p "I feel the same."
    # strokes
    p "Hey that tickles."
    n "Does it?"
    n "How about now?"
    p "That feels different."
    n "Well your breathing got heavier~"
    p "Um. Well that's your fault."
    n "Is it?"
    n "Is it really babe?"
    "She continues stroking."
    n "It {i}does{/i} look like we have a problem on our hands."
    p "Y-Yeah?"
    n "Well if I caused it, it means I have to fix it, right?"
    n "Your [mr]'s outside busy drinking, and Kaira is nowhere close."
    p "You can fix it by leaving it alone."
    n "Or, I can jack you off."
    n "You rather me go with the first option?"
    p "..."
    n "I thought so. Now let me take a look."
    # cock out
    n "Oh wow, I've been missing this."
    n "Mmmm, you just took a piss didn't you? I don't feel like tasting piss right now."
    p "You could ride me instead."
    n "Oh, Mr 'I don't want to be tickled,' now you want sex, huh?"
    n "So you want me to ride you?"
    p "Yes mommy."
    n "Well since you ask so nicely, I have to indulge, don't I?"
    p "{i}Nods{/i}"
    n "Atta boy."
    p "But be quiet!"
    n "Hahaha."
    # sex scene
    n "Oh, that was great!"
    n "Um, but it looks like you came before me this time."
    p "That's part of the strategy. If I let you cum, you'll do your bimbo scream."
    p "I can't have that."
    n "Oh yeah? But I still think I made a lot of moaning sounds... I hope your [mr] hasn't heard~"
    p "You probably moaned louder just because you're such an exhibitionist."
    n "It's called confidence, [p]."
    p "You're just showing off."
    n "Alright, enough chit chat. I'll head out first, then you follow, okay?"
    p "We've done this routine before."
    n "It's similar, isn't it?"
    n "I'll see you soon, babe."
    p "See you soon, you nymph."
    "Wow, I'm a lucky guy."
    "My, my, my, heh."
    # transition
    m "Is [p] alright?"
    n "I think so, he's just taking some time to recover."
    n "That whole experience threw him off a little!"
    m "You guys took a while!"
    n "Ah, I was just trying to help my boyfriend feel better."
    m "I see."
    n "I think he's all better now. In fact, there he is!"
    p "That hologram gave me a bit of a headache, I'm sorry."
    m "That's okay, [p]. Perhaps a drink is not such a good idea then."
    p "It's hard for me to say no, but you're right [mr]. I should hold off on the booze!"
    p "What about Kaira, is she drinking?"
    m "You know that Kaira can't take any alcohol at all! Remember the little party at the bar you guys had?"
    n "Oh yes we remember. We wouldn't want Kaira to get drunk again, would we, [p]?"
    p "Oh yeah? I thought it was kind of funny."
    n "You know how much I enjoyed it."
    m "Hey now, be responsible! I trust you to take care of Kaira, [p]. She looks up to you."
    p "Does she now?"
    m "Kaira doesn't have a father figure, as you know. Maybe she sees you as that senior male figure instead."
    p "Oh man, I don't know about that!"
    n "That makes sense, doesn't it? Maybe you can get Kaira to call you daddy~"
    p "No thank you. Maybe another time."
    m "But seriously, [p], treat Kaira well. She's a nice girl."
    p "You know I love her [mr]. Is she still at the front?"
    m "I'd think so."
    p "I'll go check on her."
    # back to cockpit
    p "Kaira! You're back in the cockpit."
    s "I'm super careful not to touch anything..."
    s "But I just couldn't resist this view. Wow!"
    s "Just... watching the clouds go by."
    p "Aww, that's cute. Those fluffy clouds, they're fluffy just like you."
    p "Let me be your co-pilot."
    p "Where would you like to go, Kaira?"
    s "I wanna go... to the beach!"
    p "The beach?"
    s "Yeah! I know we've been to the pool, but the beach is 10x better!"
    p "I'm sure we can fit it in."
    s "Where's the beach?"
    p "It's a bit far away, we'd have to drive for a bit."
    s "It's not too far away, is it?"
    p "Of course not, it's why we got a van! A relaxing RV."
    s "Awesome, when are we going?"
    p "Well, anytime you want I guess. Do you want to go there as soon as possible?"
    s "Umm... sure!"
    p "Alrighty then. Let's make that our first destination. Actually, second destination."
    s "What, why!"
    p "We have to check into the accommodation first, Kaira. Dump our stuff down."
    s "Oh like the hotels?"
    p "Yup."
    s "Hehe, I can't wait to see what rooms you've gotten for us!"
    s "You set a high expectation, [p], especially after this flight! And this beautiful view..."
    p "You always liked clouds. I remember the day you took me to that diner. You told me to look at the sky at the pretty clouds, or something."
    p "Does the sky mean something to you?"
    p "Is it potential? Does it inspire you?"
    s "Hmm, that's really deep [p]. I like the sky because... it's pretty."
    s "That's really all there is. Life is nice when things are just straight forward, don't you think?"
    p "I guess there's no need to complicate things, is there?"
    s "Yup! I just like to do what what my heart tells me. That way, you know you can't go wrong."
    p "That's a nice way of living life."
    s "It is. After all, it's brought me closer to you."
    p "What do you mean?"
    s "Sometimes, some girls are like, more shy, right? But with you, I can talk to you about really brave things! Well, most of the time."
    p "Hmm, give me an example."
    s "Remember when I asked you if I was sexy, and other naughty things I did?"
    s "I just did what my heart said, and I trusted you not to judge me and make me feel bad for it, and you didn't. Everytime you make me feel good inside."
    s "See? I just did what my heart told me to do."
    p "Ah, gotcha. Your heart belongs to me, Kaira!"
    s "Well, I wouldn't put it that way, but... it's nice, heehee!"
    p "Ahaha."
    p "..."
    s "..."
    p "..."
    s "So uh, [p], have you ever..."
    p "Hmm?"
    s "Actually, never mind, haha."
    p "Oh, alright."
    p "Do you want something to drink - ah actually [mr] wouldn't like that."
    s "That's okay [p]. Why don't we just watch the horizon together?"
    p "Sure. Sounds interesting. Look at that, a cloud."
    s "What does it look like?"
    p "Looks fluffy like you."
    s "Hehehe. What about that one? That one reminds me of pizza."
    p "Pizza, huh?"
    "This is relaxing, and I'm getting drowsy..."
    "Zzz...."
    # Sleep
    "Ah... groggy..."
    "Man, time has really passed."
    p "Kaira?"
    "She must've headed back into the cabin."
    p "Hey guys!"
    p "Guys?"
    p "!!"
    x "Happy flying, [p], and welcome to the mile high club."
    p "You were watching, huh?"
    x "Things are escalating. Events are more significant. It's coming together, [p]. Do you feel it?"
    p "What am I supposed to feel?"
    x "Temptation, lust. Of things to come and things that have past."
    x "Longing, nostalgia. Of things that have gone and will never be."
    x "Your actions have led you to this very moment in time. And I have been waiting for this."
    p "I don't understand."
    x "You enter a difficult road [p]."
    p "It doesn't feel so hard."
    x "That's the reason why it's difficult. You don't know, until it happens. Then one day, you will look back and wish you had gone a different route."
    p "Just tell me what I need to know."
    x "This route is {i}your{/i} destiny. That is all you need to know."
    x "All will be made clear. In time."
    x "Patience, [p], my old friend.... You need not wait much longer."
    # wake
    "Another dream?"
    p "Kaira!"
    p "..."
    "We both fell asleep."
    "It's evening now, we might be landing at any time. I should wake her up."
    p "Kaira, you little baby. It's time to get up now, we might be landing at any time."
    s "Hng..."
    p "Wakey wakey, little one."
    s "It's getting dark."
    p "We're landing soon."
    s "The sunset... it's sooo pwetty..."
    p "We should strap down. I'll meet you in the cabin okay?"
    s "Okay~"
    p "Atta girl."
    # transition
    n "Glad you're finally up. You slept for most of the flight. A bit of a waste for this luxury experience, don't you think?"
    p "I slept with my [sr]. Kinky right?"
    n "You should've let het climb onto you. Sleeping in separate chairs doesn't count."
    p "Anyway, where's my [mr]?"
    n "She also decided to take a nap on the bed."
    p "The bed inside?"
    n "Yes, the bed we fucked on. I wonder if she can smell the juices."
    p "That's sick."
    p "Did you get some shut-eye?"
    n "Nope. I just watched some TV and drank some wine. Great way to pass time."
    p "Let's talk more later. We're landing soon, you know. And Kaira still isn't here."
    n "Go wake her up."
    p "I did. Looks like I'll have to go again."
    p "Could you get my [mr] in the meantime?"
    n "Hey, just something before everyone's back..."
    p "Hmm?"
    # Kiss
    p "Haha, thanks."
    n "You're welcome~"
    p "But I can smell the booze in your breath."
    n "I hope it doesn't take away from my attractiveness."
    p "Don't worry, it complements it actually."
    n "Aww."
    n "Thanks [p]."
    # back together
    p "I hope you guys enjoyed the ride on this luxury experience!"
    m "It was unforgettable."
    k "I really loved it [p]! Never had I seen such a beautiful sunset before."
    n "Hahaha. So where to next?"
    p "Well, let's check into our hotel first. And after that, the beach for Kaira. Right Kaira?"
    k "Yes, I can't wait!"
    "The plane lands safely, thanks to its robust AI system."
    "We make our way towards the hotel."
    jump hotel1
