label hol_plane:
    p "Welcome. Here we are, I guess."
    m "You guess?! [p]!"
    n "Wow, you weren't lying."
    p "Why would I lie? What do you think, Kaira?"
    s "..."
    s "Ah..."
    s "This. Is. So. Awesome!!"
    s "Can we just go in?"
    p "Oh yeah it's all good. I didn't pay for service though."
    p "This whole thing is AI powered. It'll take us there, but we'll have to serve ourselves."
    m "That's good. Some bit of privacy-"
    n "..."
    m "-is always something I like to enjoy."
    s "Well, in that case, it works out, doesn't it [mr]?"
    s "I'm going to go explore!"
    m "Off you go, Kaira."
    m "Look how happy you've made her, [p]. I'm very glad to see it."
    m "You know, she's been a lot happier since you've come back."
    p "Really? I imagine she's always had this sort of happy-go-lucky."
    n "You're selling yourself short, [p]. This jet is really nice."
    n "It's so classy. I can still barely believe it."
    n "You're the guy that has my second-hand iDante phone."
    p "I'll look forward to you making it up to me."
    n "Haha! I might just follow Kaira and take a look around."
    p "We can take a good look around later, but we're taking off soon. Make yourselves comfortable and get seated for take-off."
    m "Is there a bathroom at the back? I might excuse myself before we go."
    p "Oh yeah sure, just around the back."
    m "I'll be right back."
    ## Nicole talk then rest are seated
