label van1:
    p "Yeah, this van ain't as luxurious as the plane, so what?!"
    n "No one is blaming it on you, [p]."
    p "Well I can feel the passive aggresiveness."
    m "All that matters is that we get there right? It's just point A to point B."
    m "It'll be alright, [p]. Don't worry about it!"
    p "..."
    s "I really like it, [p]! It might not be as fancy... but it's really comfy!"
    s "I feel just like one big family going on a roadrip together?"
    p "Did someone say... road trip? I got just the song..."
    play music "sounds/holiday.mp3" fadeout 1
    p "Now this is a holiday!"
    n "Isn't that song old as fuck?"
    s "I've never heard of it [p]..."
    p "Help me out here, [mr]."
    p "Please educate them for me."
    n "Whatever."
    p "Hey, I'm the one driving. I get to pick the song."
    p "By the way, I noticed you and Kaira have changed your looks a little bit."
    p "But you went with business casual like always, [mr]! What's up with that?"
    m "You're questioning my choice of attire, [p]?"
    m "I merely wanted to put something on to signifify that I was the adult of the group!"
    p "Oh hohoho!"
    m "If I were to put on some casual clothing, people would mistake me for your sister or something! Especially since I look so young, of course."
    n "Booyah."
    s "Go [mr]! You tell em'!"
    p "Fair enough."
    m "But, I heard we were going clothes shopping, aren't we? Might as well travel light to save more space for more clothes, right?"
    p "Wow, look a that, Nicole, Kaira. I was praising you guys switching it up, but [mr] has the big brains out of all of us!"
    s "Well, I think that outfit suits Nicole perfectly!"
    n "It leaves not much to the imagination. I like to make things simple."
    n "And you, Kaira? You went with a T-shirt. Sure, it's simple, but I'm sure you could have picked something more complementary!"
    s "It's a very tight T-shirt! It reminds me how much my, ahem, bewbies have grown~"
    n "We have to show those off Kaira! We'll need to do some shopping for you too."
    m "Fufufu~ you girls really take me back to when I was younger."
    m "All this naughty talk about breasts and sexiness, I feel like a young girl again!"
    n "Aww, what are you saying, Amanda, you're just like us! You fit right in."
    m "Ah, thank you Nicole."
    n "Hang on, [p], doesn't the person sitting next to the driver get to DJ?"
    n "The person sitting next to the driver... in other words, the 'shotgun'."
    play music "sounds/shotgun.mp3" fadeout 1
    s "Ooh, I know this one~!"
    m "It's certainly been on a radio a few times."
    p "..."
    p "I guess this song's alright too."
    n "Woo! Let's turn up the music!"
    s "Hey [p]! How much longer till' we at the beach!"
    p "Be patient, my little Kaira. It'll be a good few hours, so grab a drink, or take a nap."
    s "Ah! What is it so far away?"
    p "Why? I don't know why the beach is all the way over there. Go ask the beach."
    s "Hmph."
    m "Come on, Kaira, let's take a look at what goodies the van has!"
    s "Drive safely, [p]!"
    p "Yes, yes. Let me know what you find back there."
    p "Any water?"
    s "Yes!"
    p "That's going to be a life saver under the sun on the beach."
    n "Hey [p]."
    p "Yeah babe?"
    n "If I give you a blow job now, do you think you could cum quickly enough so the others don't see?"
    p "That's a big 'if', Nicky. And it would depend on how good you were."
    n "Oh, I'm plenty good."
    p "I reckon your sister's probably better."
    n "Huh? How would you know?"
    p "Don't worry, I'm just guessing. How do you think you stack up against her?"
    n "How would I know?"
    p "Maybe we should find out one day."
    n "Oh yeah? And how are you going to do that, hmm?"
    p "Oh, I've got many ideas."
    n "Tell me one~"
    p "You come over to my place and eeach get turns at sucking me off. Whoever gets me to blow the quickest wins."
    n "That's not fair, the person who sucks you second will have a harder job since you already came."
    p "Hmm good point."
    n "You're not even thinking about the actual competition. You just want to get sucked off my two hotties, don't you!"
    p "Dman, I got found."
    n "How about this..."
    n "Saffron and I get 30 seconds each. After Saffron sucks for 30 seconds, it's my turn. After my time is done, it'll be back to her."
    n "This keeps going on until you cum. Whoever gets your cum wins. How's that?"
    p "Oh man, that sounds great baby. Too bad it's all a fantasy."
    n "My sister's a bigger skank than me. She'd do it for sure."
    n "She'll want to prove her superiority... but this time, I'm going to win! Please, [p], let's make it happen."
    p "You're begging me? I should be the one begging you!"
    n "Good, good. Hmmm. I'll have to get a lot of practise in. You don't mind do you? Haha, of course you don't."
    n "But... the sleeping arrangements we have right now will make it awkward."
    n "Ah, I've got an idea."
    p "Do tell."
    n "Secret surprise. Is it going to be a bit too much? I don't know. But either way, it's gonna be great."
    p "... you're making me a bit nervous."
    n "Don't worry, I can see it coming together. It's beautiful."
    s "Hey Nicole!"
    n "Kaira?"
    s "My turn for the shotgun! I wanna pick some songs."
    n "Think on that, [p]."
    s "Well, well, well. Let's see."
    play music "sounds/think.mp3" fadeout 1
    p "Hmmm...."
    p "This is an interesting song. It's got a fun beat."
    s "It's about a girl that really really really likes this guy."
    s "Everytime she's around him, she feels light headed and her heart beats really fast."
    s "Coz she's nervous, and well, haha, I guess that happens when you really like someone!"
    s "When you really, really want someone."
    p "Sounds pretty romantic. Does the guy know about it?"
    s "Oh, she thinks he does..."
    s "But she's not sure! That's... why she's so nervous, maybe."
    p "Well if she's honest about it, then she probably doesn't have much to afraid of."
    s "Why?"
    p "Well, all you can hope is to be honst right? And if it's meant to be, then it'll happen."
    s "Hmm..."
    s "She also wants him to be happy, no matter what. She doesn't want it to be awkward for him or anything."
    s "Do you... do you think he'll like her back?"
    p "I think she doesn't need to be so nervous."
    p "After all, I'm pretty sure the guy will like her back."
    s "Oh that's good!"
    s "But sometimes, maybe she shouldn't ever tell him. Because right now, she's not sure that he knows."
    s "And maybe... that's for the better."
    p "How come?"
    s "Well, maybe because they weren't supposed to be together... like, maybe he's taken already, or for other reasons..."
    p "..."
    menu:
        "I think she should just tell him about it.":
            s "You think?"
            s "I- hmmm."
        "Maybe she should reconsider it":
            $ depravity += 1
            s "Oh, maybe you're right."
            s "She should be a bit more careful, and maybe think before acting."
    p "At the end of the day though, what ever happens, happens."
    p "Love is between two people right?"
    s "Mmm!"
    p "If there is a will, there is a way."
    s "I believe that."
    "Kaira and I shared a moment, and we smiled to ourselves."
    "With wheels spinning and music blaring, we make our way towards the beach."
    d "Make your save before this point!"
    d "This is as far as we go for the trip update for 0.54 so far."
    d "Coming up are a bunch of fun, sexy, and depraved events for you, which can be voted upon on patreon."
    d "Here's a special preview of upcoming content!"
    # beach
    # hotel sexy
    # fortuitous encounter w/ caroline
