p "Whoa!"
p "Kai'Sa?! You're the one from KDA!"
k "Aww, always nice meeting a fan."
p "I heard Popstars for the first time just the other day, my [sr] loves it."
k "It's getting quite popular. It's nice to have our song being played in clubs."
p "Sometimes, it feels like it's the only song this club plays."
k "What about it did you like?"
p "I mean, it had a nice beat and the lyrics were-"
p "Actually, I've never heard the lyrics, only the instrumental."
k "We can't have that, can we?"
p "No, no Kaisa, I'd love to here the full original song."
p "And if it's not too much, Kaisa, maybe I can see some dance moves while the song's playing!"
k "A fan meet and a dance performance?"
p "I've a large appetite. I'll be really grateful."
p "Alright, I'll show you a few moves."
k "Go get the music set up, and I'll get ready."
p "Awesome!"
## dance
k "Oh, that's what you're into, huh?" # unimpressed
p "Well, no."
p "I preordered the single, yeah."
p "A fan's gotta do their best to support, right?"
k "Well, thanks then." # still unimpressed
p "But, I'd probably keep watching the MV on YouTube."
k "We don't get that much money off of Ad Revenue." # inquisitive
p "Oh, even with over 200 million views?"
k "Nothing helps better than buying the music directly." # a little cheery
p "Yeah, but it's just music."
p "Sure you can send a message directly with the lyrics."
p "Or maybe do something with the composition."
p "I dunno anything about that."
p "But what I do know..."
k "Yeah?"
p "The way you point at the camera..."
p "The way you carry yourself when you walk..."
p "How your hands flow through the air..."
p "It's the difference between bad girl, innocent, a seductress."
p "None of that matters if you can't sell it."
k "If you can't sell it?" # intrigued
p "Anyone can point at the camera."
p "Any pleb can stomp down a runway."
p "When I see you guys dance, there's something there."
p "Something deliberate."
k "Like it was choreographed?" # smirk
p "Not just created."
p "Embraced."
p "Felt."
p "There's something visceral about the way you guys dance."
p "It's like every step comes naturally, but it's exactly the right move needed."
k "Like the move wasn't planned to match the music..."
p "But the only move the song is asking for."
k "Hmm... What are you?"
k "Some kind of dancer?"
k "A choreographer?"
p "Nah, nothing like that."
p "I think everyone can just tell when they're looking at something beautiful."
p "It just resonates with something deep within."
p "Something inside that's pure and perfect, just waiting to be left out."
k "So the song resonates with you?"
p "No, no."
p "The way you move."
k "Heh~"
k "You know~" # impressed
k "I'm the choreographer~"
p "I know." # ;D
k "Hah! Did you have that line ready to go?"
p "Yeah."
k "Heh--"
p "And no."
k "Oh yeah?"
p "It was always there."
p "Waiting to come out, just when it was needed."
k "The right moment was in some dingy bar in the middle of nowhere?"
p "The right moment was when I'm right in front of you."
k "Wow~"
k "Are you saying it's Fate?"
p "A guy can dream right?"
k "Yes, a guy certainly can."
p "Then I'd happily wear the title Dreamer."
k "Haha, you know, any fan who's seen my interview could have used that line."
p "Just like any guy can dream of this moment."
p "What matters is that you're not just a dreamer."
k "...hmm." # smirking
p "A vision and the will to bring it to life."
k "So, Mr. Dreamer."
k "My biggest fan."
k "What's your dream?"
k "And how are you bringing it to life?"
p "How I'm seeing it..."
p "Kai'Sa and I talk..."
p "We connect..."
p "and we go to the back room and see what comes after."
k "On the first date~?"
p "So we're on a date~?"
k "If I say no~?"
p "If this is Fate~"
p "If we're actually gonna be anything more than this."
p "Then we're gonna fuck eventually."
p "I don't mind getting a head start on that."
k "If I don't believe in Fate?"
p "Then trust what you're feeling."
p "It's deep inside."
p "Just waiting to come out."
p "Rumbling..."
p "Hungry..."
p "Demanding release--" # interrupt
k "Gahh... stop!"
k "That fucking interviewer." # flustered
k "It wasn't supposed to be that sexual..."
p "Maybe not then, but right now..."
p "How I'm using it..."
p "Is very sexual."
# blackout
# scene cowgirl
k "Ah..."
k "Don't... Just lie there..."
k "Move!"
p "The girl's--" # interrupt
k "Ah!"
p "The girl's supposed to be the one moving in this position."
k "Wh--Ahh--M-move!"
k "I'm your choreographer now--Mmm..."
p "Like this...?"
k "Mmm...Yeah..."
k "H-harder!"
K "Nn... D-don't pull my nips so hard..."
k "Yeah..."
k "Ahh--Ahhhh..."
k "Ah!"
k "Who...who said you could--ah--slap my ass."
p "You like that, huh~?"
k "I..."
k "I said..."
k "I said no such thing..."
k "Nn--Yeah... Like that..."
# animation?
p "Y-you're so good at this."
k "Can you f--feel it?"
k "I'm the choreo--ahh..."
k "I'm choreographer for a..."
k "Ah...Ahh..."
k "...a reason."
p "Yeah. Move that ass."
k "I-I'm the choreographer!"
k "Nn..."
p "Isn't it a choreographer's job..."
p "...to move how the audience wants?"
k "Like... this...?"
k "Yeah~"
k "You like that--ahh--don't you~?"
k "Like this~?"
k "Ahh... Nnn..."
p "Mmm... Yeah..."
k "Oh~ ...ahh"
k "Coming already~?"
p "F--I can't--I can't hang on..."
p "...anymore!"
# whitescreen?
k "Mmm..."
k "Hey~"
k "Who says you're done~?"
# She leans forward, pressing her breasts against MC chest
k "I'm nowhere close to done~"
k "Get up!"
# scene standing doggy style, camera faces Kai'Sa?
k "Nn..."
k "Yeah..."
k "You get it... right--"
k "Ah!"
k "It's--"
k "It's deep inside--"
k "So, so deep inside! Ah--"
# animation?
p "Hungry~?"
k "F-fuck yeah."
k "Give it to me!"
k "Deeper--Nn..."
k "It-It's there...Yeah..."
k "Right there--Right there."
k "Ah--Right--Nn... There..."
k "...Demanding...Release--Ahh..."
k "Ahh--"
k "Mmm... Yeah..."
# animation?
k "Uww..."
k "Yeah!"
k "Release it for me--Ahh."
k "Y-you're my biggest--Ahh..."
k "My biggest..."
k "Fuck, your cock--It's...Ahh..."
k "It's going so deep."
k "You're my biggest fan..."
k "...right~?"
k "Move!"
k "Yeah--Show me how much--"
k "Nn...How much of a fan you are..."
k "There!"
k "Ahh..."
k "Right there--Nn..."
k "Like that--"
k "Mmm--It's..."
k "It's here--"
k "F-fuck--"
k "I..."
k "I'm--"
k "Ahh... Ahh--Ahh--Nnn!"
k "I'm... coming--!"
# whitescreen
k "...Ah..."
k "Haaa..."
k "...haa..."
k "--!!"
k "Wait--No..."
k "Ahh--Nn!"
k "N-no!"
k "Stop--Mmm..."
k "Stop... It's..."
k "It's too sensitive..."
# position standing, pressed up against the wall, camera facing Kai'Sa
p "You made me do all of that~"
p "Think I'm just gonna blueball myself??"
k "F-fuck..."
k "At least... At least... Let me rest--Nnn"
p "Sounds like you want more~"
k "Ahhh--"
k "Ahh..."
k "Nnn--F-fine!"
k "Then do...do me..."
k "Fuck me!"
k "Fuck--Ahh..."
k "Fuck me with--Nnn."
k "--with everything you've got!"
# animation?
k "Haa--"
k "Yeah--"
k "Haa..."
k "Right there!"
k "Right there--Nnn..."
k "Harder--"
p "Like--"
p "This--?!"
# animation?
k "Mmm--"
k "Haa... Haa..."
k "Yes..."
k "Yes."
k "Yeah!"
k "...again..."
k "...it's--Nnn, right there!"
k "It's... coming... again--again--"
k "...again...again--"
k "C-coming..."
k "I-I'm coming..."
k "--A-again!"
# animation
p "Me... too..."
# animation?
k "In...me..."
k "Twice..."
k "Haa..."
k "Haa--"
k "That was..."
k "That was better than with Evelynn."
p "Holy fuck."
p "Can I get in on that??"
k "My biggest fan ain't fucking my best friend."
p "--Of... of course."
k "...without me."
k "...but it'd be up to you to get {i}her{/i} in the mood."
k "Until then..."
k "You're fucking me, got it?"
