label cowgirl:
    # Angelina kills a woman off and smiles
    an "My name is Angelina, knight of the holy order."
    an "Blessed by her will, I am invincible."
    an "By her will, you and your village have been judged to have violated our holy strictures."
    an "By my blade, I shall deliver your judgement."
    an "Desist, scoundrel, and do not resist, for it is a fool's errand."
    p "In this village are also chilren, innocent people who never had a chance to do anything wrong!"
    p "In the name of your order, you've persecuted so-called sinners. Folk of a different ilk than you."
    p "These people only wish to live as they are living! They should not be made to defend themselves!"
    p "Look at the world around us, do you think this is really a world of a goddess? Is this really a world where such a being can exist?!"
    p "..."
    p "The time of the holy order is over, knight."
    an "Are those your last words?"
    p "You holy knights wear your facade of piety, claiming it makes you superior beings."
    p "You claim that those who sin in the view of your order will suffer a fate of torment and torture, that worse than death."
    an "I am glad you are familiar with where I shall soon send you."
    p "No. This time, {i}you'll{/i} be paying for the destruction you have created."
    p "I, [p], will strip you of your shield, your sword and your pride! Today, I strike back against your zeal."
    an "This is your final chance. Do not resist and let judgement be delivered."
    p "Come get me!"
    an "I hope you'd say that."
    an "Ha!"
    p "Lesser spell: Weakening!"
    an "My shield suddenly felt heavier?!"
    an "You! A spell caster! Purge the witch!"
    p "Shiiit."
    p "Greater spell: immobilisation!"
    an "I can't a single muscle!"
    p "How does it feel now? To be finally against someone else with magical powers?"
    an "Just mere cheap tricks. Her will blesses me and I am unkillable."
    an "You will die as soon as the spell runs out."
    p "True, but I have no intention of killing you."
    an "Ah?!"
    p "I will give you a fate even worse than death. Now stay still."
    an "What are you planning!"
    p "Impure Alchemy..."
    p "Curse of the Daemon Bovine!"
    an "Ah!!!"
    ## Black out # naked
    an "(Where.... am I?)"
    an "(I was just fighting a man... he immobilised me... and then...)"
    an "(My memory is fuzzy...)"
    an "(Why am I naked..?)"
    an "(I hear someone is coming!)"
    an "My name is Angelina, holy knight of the order. I am vulnerable, and demand you tell me-"
    p "Hey Angelina."
    an "You were the one who incapacitated me, but as I have told you, I cannot be killed!"
    an "Now you will regret your existence!"
    p "It's far too late for that now."
    p "Take a good look at yourself."
    an "What?"
    an "I-I..."
    an "I'm... so weak... I can barely focus..."
    an "What... did you do to me?"
    p "You dont't have the energy to leave. So don't bother."
    p "Like I said, I'm giving you a fate worse than death."
    an "What... is happening..."
    p "Look at you, you've struggled so much, and only ended up tiring yourself out."
    p "Go back to sleep and gain some more energy, and we can talk about your fate tomorrow."
    an "(Somebody... help...)"
    ## sleep # boob touch
    an "(I am Angelina, knight of-)"
    an "(-the holy order?)"
    an "(Yes, that's right, the holy order...)"
    p "Wakey wakey, Angelina."
    an "You scoundrel."
    p "Scoundrel? That's no way to call your master."
    an "Cheh, I only have one mistress."
    an "Ah!"
    an "I feel even heavier than the day before!"
    p "I see the curse is doing its work."
    an "M-my body!"
    an "My breasts! What did you do to them!"
    an "Why are they so big?"
    p "The curse of the bovine. You know what that means?"
    p "Bovine means cow. That's right, your fate is to become a cowgirl."
    p "As your breasts begin to grow, your brain will start to shrink."
    p "As your hips get wider, your holiness will erode."
    p "You won't die, but you will become a creature fixated only on your own depraved desires."
    an "You are a liar! By her will, I am incorruptible! Your magic may be something, but she will protect me!"
