label amanda_studio:
        if amandalvl == 11:
            p "Just going to say hi to my [mr]."
            scene a-17 with dissolve
            v "All good man. You know the way."
            scene a-24 with dissolve
            p "Hey [mr]!"
            m "Back already?"
            p "What, you're not glad to see me?"
            scene a-28 with dissolve
            m "Yes, [p], but I've got work to do!"
            p "I think I'm going to help Vincent around with some photo work, so perhaps I've got some work to do too."
            m "Some of the other girls have photoshoots that need performed."
            scene a-30 with dissolve
            p "Yeah I know. I'll go look at that."
            jump studio_lobby
        if amandalvl == 12:
            p "Hey, [mr]! How's work?"
            m "There's a lot to get through! And how are you?"
            p "I've been so busy, [mr], but I've got a casual position at Dante Studios now, taking pictures."
            m "That's awesome! I've heard! I'm so happy you're getting something out of this too."
            p "Thanks, [mr]. Have you been in many photoshoots yet?"
            m "Yes, some basic stuff, nothing that I haven't done before. But there's exciting things coming up. Has Vincent told you?"
            p "No, he said he didn't know too much about it, and told me to ask you!"
            m "Oh, in that case, let me explain."
            m "Nyx, Maya, and I are going to have a beach themed photoshoot for the main page of Dante's website!"
            m "It's going to be a link to show off the rest of the summer collection."
            p "That's fantastic, you're rising through the ranks quickly."
            p "Does this job have something to do with me?"
            m "Yes, I requested you to be our photographer. This is just like the old times, isn't it!"
            p "Yeah, but now it'll be with two other super models."
            m "Speaking of them, what is your opinion of Nyx?"
            p "Hmm. Nyx is quite confident in herself, I feel. And rightfully so, I mean she's kind of pretty."
            m "Do you think so? Well I feel like she is too promiscuous, and I think women shouldn't be like that."
            m "Remember to not go for girls like that, okay [p]? You should pick a classy woman."
            m "Did you see her try to flirt with you in front of me? What a skank!"
            p "Well, to be fair, she didn't know I was supposed to be your boyfriend before you told her, I think she laid off quickly after that."
            m "You think so? Anyway, remember what I always say - you need a woman who not only looks good but also knows how to care for you."
            p "Yeah, got it [mr]. Tell me more about the photoshoot."
            m "Yes! This one is going to be a bit more complicated than the previous photoshoots you've had, I think."
            m "Hmm, they told me to let you know to add the 85mm lens to your collection for some more versaility in your shots."
            m "I think just show up with your camera, your lens and yourself... and let us, the {i}super models{/i} do the rest of the work."
            p "Sounds easy enough! I'll make sure I get ready then."
            m "Please! Come talk to me again when you're done and we can start the shoot!"
            $ amandalvl += 1
            jump vincent_studio
        if amandalvl == 13 and primes_85:
            p "Hey, [mr]! I got the lens so I'm all set. How are you going?"
            m "I'm going good, [p]. That's great you're ready, I wish we were as well."
            m "Could you give me and the girls some time to get ready? We just need to get changed into our swimsuits."
            p "Fair enough. Should I just wait here?"
            m "If you'll turn around while I get changed."
            p "You're going to get changed here?"
            m "Yes, this room is for everything work related."
            p "Also fair enough. Okay [mr]. I promise I won't peek."
            "Heh heh heh..."
            m "It's fine, [p]. Haven't we done this many times before? Don't forget, you've even seen me naked many times when you were young!"
            p "Wow, [mr], you're really taking this boyfriend-girlfriend roleplay to the extreme here. If I weren't myself I'd say you're hitting on me!"
            m "Oooh? And so what if I am?"
            p "I would say, bring it lady. Show me what ya got. Don't tell me that being Dante's model is just for show!"
            m "You're a cheeky boy, [p], but you really know how to make a woman feel special, I'll tell you that!"
            m "It'll be good if you can keep this up around Nyx, that'll show her that I've still got what it takes..."
            p "Hahaha. Go, get changed! We've got a shoot to do."
            m "Alright, alright."
            ## change
            "Alright [p]. You know the drill."
            menu:
                "Peek.":
                    $ depravity += 1
                    "Hnng!"
                "Wait.":
                    "I'm not perving on my [mr] today!"
            m "I'm ready, [p], aren't you excited, let's go!"
            # transition
            p "This place is actually massive. I was here the other day taking a few pictures for Maya."
            p "This screen here is new though. It must be for the beach theme."
            m "That's right, [p]."
            p "So when are the other models getting here?"
            ny "Looks like we're right on cue."
            "Holy... damn."
            ma "You look great, Amanda!"
            "Yeah well you guys look great too."
            m "Oh thanks girls! I see you guys have gone with a matching outfit!"
            ny "Yes, we thought we'd look cute. I hope you'll agree."
            p "For sure! I'm loving it. Both of you girls look excellent"
            m "Ahem, [p]?"
            p "I mean, erm. I've said too much."
            "Damn, [mr] is snippy today."
            ny "Amanda really has you on a leash, hasn't she [p]?"
            p "It's not like that, really."
            m "Let's be a litte professional here, girls. We're here to do a photoshoot."
            "It got serious real quick."
            p "Okay okay ladies, one at a time, alright? And I'm talking about the photos."
            p "We'll do some pictures of you guys individually, then as a group. How does that sound?"
            ma "You're the photographer, [p]."
            ny "Maya's right. Give us some directions, like I taught you to."
            p "Okay. Which one you first?"
            m "That's up to you, [p]!"
            p "Fine. How about you first then, [mr]- I mean, girlfriend? We were the first here, after all."
            "Shit that was close!"
            m "Alright, let's go. This is so surreal, having you around while I'm working."
            p "I bet you didn't see us working together, did you, [mr]?"
            "Oh shit I did it again!"
            m "Ahaha! My boyfriend meant to say mommy. He's into women with motherly instincts who can care for him."
            p "Uh, yes! That's why I call her [mr]. Not for any other reason, nope!"
            ma "It is very curious indeed. What do you think, Nyx?"
            ny "I think I could be very motherly too if it came to it."
            p "Anyway! Let's get back to work! Amanda, why don't you start posing?"
            p "Let's get a few quick ones."
            m "(I have a strange feeling as [p] is taking pictures of my body.)"
            m "(I feel like I'm the centre of attention, and everyone is looking at me. This is why I chose to be a model!)"
            m "(Are you watching Nyx? Maya? This is a strange feeling, but I love it.)"
            p "You look beautiful, Amanda."
            ma "I agree, but let's move on a little, shall we? Or we will never get to the group shots."
            p "The exotic Maya has spoken. Sorry Amanda, we'll get right back to you soon."
            m "I'm looking forward to it!"
            ma "So [p], let's put your photography skills to the test."
            p "I hope you'll see I've improved."
            p "Looking fantastic, Maya! Let's get one with you with your hands in front of your chest, looking demure."
            p "The boys will lap this up."
            p "This should be enough. Come on up Nyx, it's your turn."
            ny "Let's show the other girls what we got."
            ny "Give me a few directions, [p], like I taught you."
            p "Alright. Look at the camera liek you want to have sex with it."
            ny "With pleasure."
            m "(Oh my god, what is Nyx teaching [p] to say?)"
            p "Seductive! Now let's amp it up even more!"
            ny "Well, there's only one way to dial the temperature up~"
            p "What a scoop!"
            m "(I can't believe Nyx is playing with [p] right in front of me! How dare she? [p] is {i}my{/i} boyfriend!)"
            m "Hang on, stop this right now!"
            m "[p], there's something I need to do, and I need you to come with me. It's urgent."
            p "We won't be too long, we just need to do the group shot-"
            m "No ifs, ands, or buts young man!"
            m "We're going now!"
            p "Alright, alright. Sorry girls, um... we'll finish this at a later time."
            # exit
            ny "Oh?"
            ma "You should have shown some more sensitivity, Nyx."
            ny "But this is how I work, Maya. Seduction sells. You're far too innocent to know. You should be more like me."
            ma "Whatever it is, you've upset Amanda now. We'll have to make it up to them."
            ma "And besides, it's because I'm not like you that you like me so much. You wouldn't want that to change."
            ny "I guess you're right~"
            # back to mc
            p "What's the big idea, [mr]? Is something up?"
            m "You know what you've done, young man."
            p "..."
            m "I think that Nyx is setting a very bad example for you."
            m "I'm supposed to be your girlfriend, but even then she was flirting with you! Right in front of me!"
            p "She's a super model, [mr]. How often do I get to be in the same room as a super model? And to be with someone playful like Nyx-"
            m "You know who else is a super model? Me, [p], me!"
            m "She's not that much better than me, is she? I've still got it, haven't I? It's what you've always said."
            p "Oh, [mr]..."
            p "Of course you're beautiful too, but its different."
            m "Nyx is going to think that I'm a cuckqueen pushover who lets other women flirt with their own man."
            p "Nyx is sexy hot. It's true. You are hot too, but people don't just flirt with their own [mr] like that as naturally."
            p "I'm sorry for the shitty act. I'll make sure to pretend you're my girlfriend more."
            m "...pretend?"
            m "Oh [p], I'm sorry. It's not just that..."
            m "Sometimes, I can't help but feel like I'm... inferior, like my days are behind me already."
            p "That's not true, [mr]! You're a super model!"
            m "Like the rest of the girls?"
            p "Of course."
            m "I have the same sex appeal as the other girls?"
            p "That's why you're modelling with them."
            m "Then why don't you flirt with me the same way you flirt with Nyx? If she turns you on, I should turn you on too, right?"
            p "Physically, for sure. I mean, if you weren't my [mr], then-"
            m "I see that you're always smiling and jigged up physically around Nyx. Physcially, it should be the same for me too, right?"
            m "Prove it to me, [p]."
            p "Hang on, [mr], what do you mean?"
            m "Drop your pants, young man."
            p "What are you saying?!"
            m "It's nothing we haven't seen many times before. Don't make me say it twice, [p]!"
            p "...fine. Alright."
            m "(Oh my god...)"
            m "(He has such a good size! It's just like when I saw him and Nicole having sex in the living room...)"
            m "(...the strength and virility of a young man.)"
            m "(I want it... all to myself.)"
            p "I'm sorry you have to see this [mr], I'm a guy after all. Sometimes I can't help it."
            p "Err, [mr]?"
            "Wordlessly, she dropped to her knees and appraoched my member gingerly."
            m "It... looks a bit tense, [p]. I'm sorry for doing this to you."
            p "N-not a problem... [mr]."
            m "Won't you... let me help you with... that?"
            m "After all, it's just-"
            m "..."
            m "...been so long since I- since I...."
            "For some reason, I did nothing as her hands delicately glided across my shaft."
            m "D-does this make it feel better?"
            p "Ahhh..."
            m "I, I don't know what I'm doing, sorry. It's just been too long."
            p "No... [mr]?"
            # focus on amanda's face
            p "Please... go on."
            # Smile
            m "I'm glad, [p]. Let me help you unload that stress~"
            # sex scene
            p "Wow, [mr], wow. We just crossed a line into depravtity."
            m "Any regrets?"
            menu:
                "Yes":
                    p "I don't know. We will never be able to go back."
                    p "What will this mean for us?"
                "No":
                    $ depravity += 1
                    n "No. To tell you the truth, it's been something I wanted to do."
                    m "You and I both, [p]."
            m "Look, I think it'll be good if we take this slowly. I don't know, this is new territory for me."
            p "Me too! What about you? Any regrets?"
            m "..."
            m "I felt like woman today, [p]. You made me feel like a true woman again, like you said, it took crossing the line over into depravity to do that."
            p "I think there are still a few more lines left to cross."
            m "You know, I don't know how I feel about that. What we did today was... special, but sometimes when we give in to our temptations, things don't work out."
            p "..."
            m "If we go any further, we'll never be able to go back. I don't think I'm ready for that."
            "Fuck, my [mr] was so eager to blow me and now she's having second thoughts?"
            "It feels bad, being rejected by my own [mr]."
            p "Yeah, I got something to do anyway, [mr]. It's getting late."
            m "We'll talk again later."
            scene black with fade
            "Wow, what a day. What a day indeed."
            $ amandalvl += 1
            jump amanda_room
        if amandalvl == 14:
            p "Hey, [mr]."
            m "Oh, [p], it's you."
            "It's me?"
            p "So how has your day been?"
            m "Well, it just started, so there's nothing really exciting going on."
            "This is awkward. Who's going to address the elephant in the room?"
            p "..."
            m "..."
            p "Um, [mr]? I was thinking about what happened the other-"
            m "Wait-let me just say something first."
            m "I was also thinking, [p], and I am sorry for what happened. Let's put this behind us and forget everything."
            p "What? But you were the one who-!"
            m "It was my bad! I fell prey to my temptations but it won't happen again, I promise. I don't want to talk about it anymore."
            m "That day never existed."
            p "..."
            m "I think I should go back to work now."
            p "Alright, I'll go."
            "Fuck, this is so embarrassing!"
            $ amandalvl += 1
            jump studio_lobby
        if amandalvl == 17:
            "The aphrodisiac, I can't wait to try it on [mr]."
            play music "sounds/alchemy.mp3" fadeout 1
            v "You look like you're in a bit of a rush, [p]!"
            p "I'm seeing Amanda, Vincent."
            v "Must be an emergency."
            p "Erm, not really. What's up?"
            v "Huh? It just looks like you've got something to do. You're giving off those vibes, bro."
            p "Watcha goin' to do with your [mr]?"
            "Damn, is my depravity so plain to see?"
            p "I'm... in no more of a rush than I usually am."
            v "Mate, I'm just shit talking. Don't let me hold you back, haha."
            p "Oh. Right."
            v "You okay man? You're looking a bit anxious."
            p "Me?"
            "I have no idea what I'm about to do. Should I reconsider what I'm going to-"
            v "Yeah, [p], you. What's going on, brother?"
            "Oh my god, what am I thinking. Was I really about to try and use the aphrodisiac for [mr] to have sex with me?"
            "This can't be right... can it?"
            menu:
                "There's nothing wrong.":
                    $ depravity += 1
                    "It's going to be fine. She wants it anyway. She just doesn't know it yet."
                    p "There's nothing going on Vince."
                "There's something wrong.":
                    "There's something wrong with the picture here."
                    "Was I always like this?"
                    p "You're onto something Vincent."
                    p "There's something I'm apprehensive about."
                    "It might be wrong, but I'm going to do it anyway."
                    p "But there's nothing you can do for me now."
            v "If you say so man."
            v "Just let me know if you need someone to talk to, alright?"
            v "Just like old times!"
            p "Thanks."
            scene black with fade
            "Sometimes when you do something you're not supposed to, you become extra self-concious."
            "I need to calm down, or this might not go smoothly at all."
            "Breathe in.... breathe out..."
            p "Hello, [mr]."
            m "Good to see you, [p]."
            m "Are you here to do a job or something?"
            m "How is Dante Studios treating you?"
            p "I'm not here for that, [mr]. I'm here for something else."
            p "There's something I want to show you."
            m "Something to show me? Oh, I'm excited to see!"
            p "I'm glad you think so. But first, you need to uh, go over to that corner and turn around, and don't look until I say so."
            m "Turn around? Don't be silly, [p]! You can just show me here!"
            p "Please, [mr], for this to work, you need to turn around."
            m "You're acting strangely, [p], is this some sort of prank?"
            "Oh what am I thinking? I don't even have confidence that this aphrodisiac will work!"
            "What if Nyx and Maya are just pretending?"
            "Oh my god. Don't tell me they're playing me, and just putting tension between me and [mr]."
            "This might end up just a dumb prank - with me being the fool."
            p "P-prank?"
            "No! It's too late, I've gone all in so far. Nothing ventured, nothing gained."
            p "Look [mr], you'll understand when you see."
            m "This isn't about what we agreed to not talk about, is it?"
            p "..."
            m "Well is it?"
            p "It's not, [mr]. This is not that. It's different okay?"
            m "...okay."
            m "I'm facing the corner now and can't see you. You can do your magic trick now."
            "Oh but Amanda, if only you knew what kind of magic trick this was."
            # fap
            p "{i}Rub rub rub rub{/i}"
            m "Hey, what is that sound?"
            "Aww fuck I'm definitely all in now. This had better work!!"
            "But I need to get 100% hard first."
            p "Almost ready, just hang on."
            "Fuck think of something sexy! I'm picturing..."
            "You, [mr], with your sexy curves and voluptuous tits."
            "That ass, oh with those wide, child-bearing hips."
            "Oh yes, oh yes."
            p "Ah, [mr]... you can... turn around now."
            # turn
            m "What's the big-"
            m "WHAT THE FUCK?!"
            m "What are you doing young man?!"
            p "It-it's not working?!"
            m "What's not working? What exactly are you planning to do here, [p]!"
            "Oh fuck I fucked up hard."
            m "Why are you showing me your-"
            m "...dick?"
            m "That juicy, thick, manly dick..."
            p "Eh?"
            m "What... is going on... I feel hot... thirsty..."
            "The aphrodisiac is working. But remember what Nyx and Maya said..."
            "If [mr] cums, the aphrodisiac will stop working. But until then, the aphrodisiac effect will kick in whenever I whip out my cock."
            p "What are you after, [mr]?"
            m "I'm after your cock, [p], and I just-"
            m "..."
            m "I just want to have a small taste... just a small one..."
            "She crept towards me with a glazed eyes that could only see one thing: cock."
            "Back when Nyx and Maya were affected by the aphrodisiac, they chose to make up with each other instead of me."
            "This means that they don't 100% lose control of themselves."
            "Based on [mr]'s worship of my cock, does this mean that she's got part of her that desperately wants to be fucked?"
            m "Mmmm..."
            # BJ
            "Oh fuck!"
            m "Ah~ the sperm is all over my face, and for some reason I feel even hotter than before~!"
            "Oh shit, this was what Nyx had experienced too! But if I put my pants back on, maybe the effect will die down."
            m "Oh [p], i Feel-"
            m "Better?"
            p "Hello [mr]. You blew mem, and you did a great job."
            m "I-I couldn't control myself! I am truly a wicked, depraved woman!"
            p "No no no, what just happened was great. Don't you understand, [mr]?"
            p "We can do this, and still go back to being normal, whatever that means."
            p "We should be allowed to live and love."
            m "These things are just... physical, [p]. And it was a physical temptation that overcame me."
            p "But we love each other too! How many times have we told each other."
            p "I love you I love you I love you, we say it all the time!"
            m "This is in a different way."
            m "We'll pretend this never happened."
            p "That's what you said last time."
            m "I just... want to go back to how things were."
            m "..."
            m "Thanks for visiting me, [p], but [mr] has got some work to do. I'll see you back at home, alright?"
            p "..."
            "Just like that, she surpresses it."
            p "Alright [mr], keep going strong, and I'll support you all the way!"
            m "Thanks!"
            scene black with fade
            "It's a bit of a sorry sight, with [mr] pretending everything's normal while my cum is splashed over her face."
            "But just wait [mr], I'll show you that some things are worth confronting."
            call daykeep
            jump map
        else:
            v "Ooh, Amanda isn't available right now."
            v "Try again later!"
            jump studio_lobby
