default vincent_work = 1
label vincent_studio:
    menu:
        "Talk":
            if amandalvl == 11:
                p "Just going to say hi to my [mr]."
                v "All good man. You know the way."
                p "Hey [mr]!"
                m "Back already?"
                p "What, you're not glad to see me?"
                m "Yes, [p], but I've got work to do!"
                p "I think I'm going to help Vincent around with some photo work, so perhaps I've got some work to do too."
                m "Some of the other girls have photoshoots to do."
                p "Yeah I know. I'll go look at that."
        "Work":
            if amandalvl == 11 and vincent_work == 1:
                v "[p]!"
                v "I was thinking about that work I got for ya."
                v "The pay rate will probably start off on the low side, considering you're a beginner."
                p "That's fine. Slow and steady."
                v "I'm glad you understand."
                v "Nyx has a photoshoot coming up soon, and we're looking for some close up shots of her face."
                v "Standard close ups. Centre the face, then just click."
                p "Sounds easy enough."
                p "I have a camera and lens already."
                v "We're looking for a more specific kind of shot."
                v "You'll need one of those low aperture lens. Hmm, something like 50mm primes."
                p "Yeah, I'll look into that."
                v "Come talk to me again when you've got the goods."
                $ vincent_work += 1
                jump studio_lobby
            if amandalvl == 11 and vincent_work == 2:
                if primes_50:
                    p "Hey, I got those lens."
                    v "The 50mm prime lens - also known as the nifty fifty."
                    v "Did you know, [p]? They are reknowned for their versatiltiy."
                    v "Surely, a must-have for all kinds of photographers."
                    p "Cool. Can you tell me more about the next photoshoot?"
                    v "It's with the beautiful Nyx. We need some close shots of the head."
                    p "Just the head?"
                    v "Hmm, I'd say collar bones and up. You know?"
                    v "Nyx is experienced at this stuff anyway. She'll let you know what to do, I'm sure."
                    p "Okay, sounds good."
                    v "Don't be nervous alright? Haha. It's gonna be fine."
                    p "I can't believe it. I'm about to be the photographer of a famous model."
                    v "Photographer in a very controlled situation with a narrow scope."
                    v "Slow and steady, right?"
                    p "Right. I got it."
                    v "Ready? I'll show you the way."
                    scene black with fade
                    v "Just through here mate. The next voice you hear will be Nyx's."
                    p "Jesus Christ this is formal."
                    ny "Vincent you're finally here. Let's get this shoot over with."
                    ny "..."
                    ny "You're not Vincent."
                    p "It's [p]. We've met earlier."
                    ny "You're Amanda's boyfriend."
                    p "..."
                    p "That's right. I'm a little new to the job, but I'm also your photographer for today."
                    p "Nice to meet you, hahaha..."
                    ny "Really? By the way, won't Amanda be jealous if her boyfriend is photographing other beautiful women?"
                    p "Haha, do you think so?"
                    ny "Well after all, she seemed {i}so{/i} protective of you."
                    p "Yeah I can see how it comes across that way. You could almost say like a... motherly instinct."
                    "Oh man, I regret that pun already."
                    ny "In any case, let's start shall we? Usually it's the photographer giving directions, but since you're new..."
                    ny "I don't mind having the tables turned a little."
                    p "Thank you for your generosity."
                    p "Now let's see..."
                    p "Just uh... look at the camera here..."
                    p "Great shot. Now, what else..."
                    ny "I think Vincent gave you an easy shoot by just focusing on the face, front on."
                    ny "But even then, there are variations."
                    ny "Usually you can vary it up a bit by asking the model to change their facial expression."
                    ny "How about asking me to put on a more fierce expression?"
                    p "Uhh... such as?"
                    ny "Hey Nyx, give me a fierce gaze sharper than glass and a pout that could seduce even women."
                    ny "...like that."
                    p "Okay, sure..."
                    p "Let's try a look so fierce I feel like I'm being stabbed by a thousand daggers."
                    ny "Interesting description... let's see."
                    p "Great. Now how about biting your lips at the same time?"
                    p "Great shots!"
                    p "Now the pout!"
                    p "Oh you look so good."
                    ny "A photographer's job is made easier by a good model. This is fun, isn't it?"
                    p "I woulnd't mind doing more."
                    ny "There are more chances down the line. Dante's models are not just known for attractiveness, but also sex appeal."
                    ny "If you're into that sort of thing, I'm sure Vincent can arrange it."
                    p "Oh I am!"
                    ny "Don't sound {i}too{/i} eager, [p]. Remember Amanda."
                    p "Right."
                    ny "Till next time."
                    scene black with fade
                    v "How was the work?"
                    v "Feeling tired?"
                    p "Hardly man. This stuff is great. Here are the shots."
                    v "I'll take a look later, I'm sure they're good."
                    v "Here's the pay for this job. Not too bad, right?"
                    "You have gained $100!"
                    $ cash += 100
                    p "Sweet."
                    v "Come back next time, [p]. See if I can find you more work."
                    $ vincent_work += 1
                    call daykeep
                    jump map
                else:
                    v "Sorry, [p]. We need those 50mm primes."
                    jump studio_lobby
            if amandalvl == 11 and vincent_work == 3:
                v "Interesting stuff, [p]."
                v "We need a few shots of Maya to go on our website."
                v "Portrait shots. Nothing too hard."
                p "Does she have to look formal and serious?"
                v "Erm. Maybe one with a faint smile?"
                v "It's just a passport style picture."
                v "You're the photographer, [p], use your judgement."
                p "Alright, can do."
                v "It'll be against a white background. Let me take you to the studio."
                scene black with fade
                v "Just here, mate. Good luck!"
                p "Thanks, Vince."
                ma "Nyx told me about you, [p]."
                p "Good things?"
                ma "Haha! Something about being an up and coming photographer for Dante studios?"
                ma "We have a great work culture here. The photographers treat the models well, ane vice versa."
                p "Sounds awesome."
                ma "We're actually looking for a portrait shot of me to go up on the website on the page where the models are listed."
                ma "It'll have a lot of other models up there too, so make sure I stand out!"
                p "I can't imagine that would be difficult for you."
                ma "Hmm?"
                p "I mean, you have those ears, right? It's a very... exotic look."
                p "Are those elf ears?"
                ma "Ears? Is something the matter with my ears?"
                p "..."
                p "Yeah. Are those like, prosthetics or something?"
                ma "Prosthetics?"
                p "I mean they're like... pointier than the average person's."
                ma "Oh, I suppose you're right. I've never really thought about it."
                p "So they're not prosthetics...?"
                ma "I don't think so, I've had them for as long as I remember."
                p "Okay..."
                p "Anyway, that's what I meant when I said they help you stand out."
                ma "Ah, I suppose that makes sense."
                "This conversation makes no sense."
                p "I don't know why I brought it up, sorry. Let's continue on, haha."
                p "So, I think just a portrait shot, right?"
                ma "Yes, but let's also get a little bit creative."
                ma "Why don't you just start off with a basic shot of me standing still?"
                p "Alright, done."
