label future:
    call hidescreens from _call_hidescreens_10
    hide screen player_room
    if nicolelvl == 6:
        scene black
        play music "sounds/cyberpunk.mp3"
        scene future with flash
        x "Sleeping well, [p]?"
        x "No doubt, after all, with your romantic escapades with Nicole, who wouldn't be sleeping easy?"
        x "She is without doubt a temptress."
        x "Is it blind hedonism that she chases after, or is there something more?"
        x "Is it possible to sink into depravity, and yet remain virtuous?"
        x "Learn more about her, so that you can learn more about yourself."
        scene black with fade
        "Am I still dreaming?"
        $ nicolelvl += 1
        return
    if kairalvl == 5: ## dream sex
        scene black
        play music "sounds/alchemy.mp3"
        # Next time MC goes to bed:
        "Okay time to get some sleep"
        # Hears door open slowly
        "Oh, I almost forgot that Kaira would come tonight"
        s "Hey, [p]. Ready for our sleepover?"
        p "Yes, Kaira. But I'm actually really tired."
        s "Don't worry. I'm really tired too."
        p "Uh... I think you forgot most of your pajamas for the pajamas party."
        s "Hehehe you know I don't like sleeping in a lot of clothes."
        "It's going to make things a lot... harder..."
        p "I just thought it might be different when we're going to sleep in the same bed."
        s "No, silly. You don't mind, do you?"
        p "No, Kaira, just get into bed."
        ## Kaira gets into the bed next to MC
        p "Once again you were right. This actually feels really nice."
        s "I got an idea that could make it even nicer."
        p "What's that?"
        s "Will you hold me tonight?"
        s "(I want- no... NEED to feel him touching me."
        p "Sure, Kaira."
        ## MC spoons Kaira
        s "This is a lot better. I feel so secure with your arms around me."
        p "I like it a lot, too."
        "I'm not sure if this is right or wrong, but it feels so nice to have Kaira next to me."
        "Her breathing gently, I feel her chest and back shift ever so slightly as she breathes in."
        "It's oddly comforting. And Right? Wrong?"
        "To feel the warmth of her under my fingers, the softness, the silk. How could anyone say this is wrong?"
        "Nobody will know, so who cares?"
        scene black with fade ## Dream sequence
        s "Shh. You'll wake [mr] up. Trust me."
        p "Kaira!"
        "She pressed her lips against mine in an effort to silence my whispers. Meanwhile she guided my hand down her body, between the satin of her breasts."
        "Across the tender softness of her stomach, down further still until I felt the hem of fabric cross the tops of my fingers, and then… Heat and Silk!"
        "I felt her push my hand down to her crevice. As my fingers brushed over her, she pulled her lips away from mine and sucked in a sharp breath."
        s "I've wanted this for so long. Keep going."
        "We both knew what was going on. Explanations and awkward dialogue had no place here."
        "Our biology transcended all other communication."
        "My fingers slid further between her legs, and I felt the swollen edges of her clit brush between my fingers."
        "I trailed my fingers between her lips, parting them softly feeling the heat escape with each passing caress."
        "I ran my middle finger across the length of her slit, and it found its course within its depths."
        "Is this... her first?"
        s "Aaa, [p]..."
        "The erotic sigh that arouse from her mouth; soft and sensual. It made me harder than stone and I ached to be within her."
        "But I held back. This moment was not about me..."
        "I ushered my to fingers to return to their work- Moving swiftly, yet gently as they drew some of her moisture from within."
        "I felt her juices coat my fingers and could only imagine how it would feel on my cock."
        "Her chest rose and fell as she let out breathless labored gasps of air, trying to remain silent herself."
        s "[p]! I- didn't know-"
        s "That it could feel... so good!"
        p "My fingers are more than happy to oblige."
        "I picked up the pace and her gasping breaths followed."
        "Then suddenly-!"
        s "I- ahhh!"
        "She buckled under my touch."
        p "Kaira, oh, I think you just had an orgasm."
        p "Have you had one of those before?"
        s "No- not like this!"
        s "Eek!"
        "She was so precious as she was shuddering in ecstasy."
        "Isn't it amazing how such an outwardly innocent and naive girl can be such a minx in reality?"
        p "Was I your first, Kaira?"
        s "..."
        s "To be fair, I still haven't had anyone yet."
        p "Oh."
        s "Can, I [p]? Please?"
        p "Well Kaira, you're going to have to ask for what you want."
        s "I... want more. I want your cock in my... pussy."
        p "How come? Didn't you just cum?"
        s "I want to cum again and again and again!"
        s "I want your penis. [p]. Do you know how long I've wanted to hold it, kiss it, and insert it into my pussy for?"
        s "I've been thinking of it since the bar - I still remember it!"
        p "All this time, huh? You naughty girl you, you were pretending to have forgotten."
        s "I don't want to pretend anymore, [p]."
        s "My pussy's so wet, even wetter than that day."
        s "Please, take my virginity. I want it to be you."
        s "Please let me be your woman!"
        p "Kaira..."
        s "I'll... open myself to you."
        "What a perfect pussy. I... can't reist the urge to plunge myself into the depths of that nectar."
        "This... is how it's meant to be."
        s "I love you [p]! No matter what anyone else says."
        p "You will be mine, forever."
        ## Wake up
        p "Good morning, Kaira."
        s "Oooh! Yawn."
        s "(Wait, what is that pushing aginast me, is that his-?)"
        "She shifted briefly against me and I felt the skin of her butt brush against the head of my cock. Somehow in the night my shorts must have shifted. My cock sprung from my shorts and slid gently between her cheeks."
        "I tensed. She tensed."
        s "Good morning [p]."
        "She pushes her body against me pressing my cock a bit deeper between her cheeks."
        p "Did you sleep well?"
        "I try to slide away, hoping she didn't notice our current situation. But she kept herself pressed against me."
        "I could feel heat on the head of my cock. Surely she had to feel it. What's she doing?!"
        s "I slept {i}very{/i} well."
        s "Did you?"
        p "I don't know, I'm still trying to figure it all out."
        s "Figure what out?"
        p "It's... hey you know what? It's morning, get out of here!"
        p "Who knows who's going to barge into the door and think we're up to some funny business."
        s "Well, [p], you're going to have to tell me all about this funny business later okay!"
        "She slides away from me, releasing me from my anxious torture."
        p "That did not just happen... Between this morning, and that dream..."
        ## corridor
        s "(That dream was so real. His hand darting back and forth. Wow, what a rush,. And this morning, what was I doing?)"
        s "(Clearly he was uncomfortable, but it felt so nice to be pressed so close to him.)"
        s "(I didn't want to leave, hmmm. Maybe I'll have another sleepover sometime soon!"
        $ kairalvl += 1
        return
        
    if kairalvl == 6:
        scene black
        play music "sounds/cyberpunk.mp3"
        scene future with flash
        p "Not again."
        x "Feeling conflicted? [p]?"
        x "Let's be honest [p]. You've always had feelings for your [sr], Kaira."
        p "It's not like that."
        p "It's... confusing."
        x "It's inevitable."
        x "It's already happened before."
        p "It's not right. I {i}know{/i} it's not right."
        p "Can I even fight the depravity?"
        x "It cannot be fought, but how you sink in, is up to you."
        p "Then what's the point?"
        p "Nothing I do will change how it ends anyway!"
        p "This dreams keep haunting me. I need to wake up now!"
        x "As you wish. The way out is this way."
        scene black with fade
        stop music
        "Then suddenly, darkness."
        "Is it over now?"
        "I see... is that?"
        p "...Kaira?"
        p "Kaira! Can you hear me?"
        "..."
        "She's not moving."
        "...I must be dreaming, but this seems so real."
        "..."
        "Right now, I can do anything to her, and I can just wake up afterwards."
        "Surely, here of all places, I can give in to my desires."
        "Do I dare?"
        menu nochoice:
            "Have your way with her.":
                $ depravity += 1
            "I can't.":
                "..."
                "But there appears no way out."
                "I have to give in."
        ## fondle boys
