label nicoleBathhouse:
    n "Ah, you're here [p]!"
    p "Whoa, uh..."
    n "Making a lady wait, tut tut."
    n "Scratch that Nicole, you look amazing!"
    p "I got here as quickly as I could, believe me."
    p "What do you think of the place?"
    p "It's pretty fancy right?"
    n "The music's nice."
    n "I like the way it floats around the lobby."
    n "Makes everything seem grand."
    p "I knew you'd appreciate it."
    n "I heard it was a luxury resort, so I went a little classy."
    n "The thong is riding a bit too high though..."
    p "That was no accident."
    p "Did you bring your swimwear?"
    n "No? I thought I'd just hop in naked."
    p "It's a public space, people might see you!"
    n "I'm kidding!"
    p "Wow."
    n "Of course I brought some clothes."
    n "Question is, how slutty are the clothes I brought?"
    p "As long as it covers the important bits, as you say."
    p "Anyway, let's move on."
    p "Hey Camille, could you sign us in into the bathhouse?"
    t "...yes! Of course!"
    t "This way please!"
    t "We're here."
    t "The changing rooms are just next door. Remember to enjoy yourselves!"
    n "Wow, this place is big!"
    p "We'll get to dive in real soon."
    p "Why don't you go get changed? I'll meet you back here."
    n "Go get changed quickly, I don't want to be waiting for you this time!"
    "..."
    "Done!"
    "I see Nicole is taking her time."
    "I think Nicole is quite into me."
    "I wonder if she's latching onto the 'depraved' part of me."
    "Either way, I'm enjoying it now."
    "I'm glad I finally caught a break."
    n "Hiya!"
    p "You look fantastic."
    n "I always look fantastic, [p]."
    n "When have I ever not?"
    p "Look, the water's ready."
    n "I think I'm going to take my time."
    n "I've always had bad experiences with jumping into water. It's either too hot or too cold."
    p "Hey, take a look at that over there."
    n "That over where?"
    "{i}PUSH{/i}"
    n "Ahh!"
    p "Hahaha!"
    p "Got you back from the time you pushed me in the changing room!"
    n "Didn't I make it up to you by sucking your dick?"
    n "What are you going to do for me this time?"
    p "Cannonball!!!"
    n "My hair!"
    n "..."
    n "Hahaha!"
    p "Aa!"
    n "Ooh, not afraid to get a little rough are you?"
    n "Come on, what's stopping you?"
    p "There are still people here."
    n "Too bad~"
    n "Look at you, such a rough man!"
    n "You've pushed my bra apart."
    "Nicole's breasts are really so beautiful..."
    "I don't care if they're fake."
    n "Didn't you just say people are still here?"
    n "You can stare another time."
    n "Let's splash around a bit more."
    n "Woo!"
    "Seeing her so happy gives me a wholesome feeling."
    "There's always a tension around her, and she's always well composed."
    "But now it looks like she's genuinely having fun."
    n "Look at me, I'm so high!"
    n "The water here's a lot hotter too!"
    p "Careful, Nicole!"
    p "Don't hurt yourself."
    n "Oh I can take care of myself!"
    n "Catch me if you can!"
    n "Too slow."
    p "You're a slippery one!"
    p "Haaa!"
    n "Hey. [p]."
    n "I've got a favour to ask you."
    p "What is it?"
    n "Um, I think my panties came off when I jumped down."
    n "Do you think you could dive down and look for them?"
    p "Sure."
    p "I am a gentleman, after all."
    "..."
    "I don't see no panties down here, but damn..."
    "That's a nice view."
    "I wonder if she even dropped them for real."
    "What a tease."
    "I might just look for a few more seconds..."
    "Alright, time to go back up."
    n "You held your breath for a long time, did you find anything?"
    p "Not the panties, but I did find something else to look at."
    n "Did you like it?"
    p "You're such a tease."
    n "I don't have to {i}just{/i} be a tease."
    p "Thats very true."
    n "Since you're a gentleman, won't you give me your pants so I can use it to cover myself up?"
    p "You dirty little minx."
    n "You wouldn't have your girlfriend parading herself to other men would you?"
    p "Won't happen, there's no one besides us in the bath house now."
    n "In that case, [p], I say you you skewer me with your thick cock right here, right now."
    p "People might walk in, it's still- "
    n "I always have to do everything myself."
    p "Huh?"
    n "(Time to get you out of there.)"
    n "(Get up for me you stud.)"
    "Oh my god, she's actually sucking me off in the middle of the pool."
    "The water makes it rougher and it's more sensitive!"
    n "You're nice and hard now, and sucking while holding my breath is actually quite hard."
    p "Let's not wait any longer, come here you minx!"
    n "Ahh!!~"
    n "Ooooh!"
    n "Y-you didn't even give me any warning!"
    p "I knew you were already lubed up."
    n "I'm horny but- ah!"
    n "But the water washes it out- ah~!"
    n "The water washes it out a bit!"
    p "Let's fuck on dry land then."
