default gym_intro = False
default veronicalvl = 0
default olivialvl = 0
label gym:
    if gym_intro == False:
        jump gym_intro
        $ gym_intro = True
        "Man this gym is hard to find."
        "Trying to get there is a workout in and of itself!"
        "Hang on... I think this is it."
        "Huh. It's smaller than I expected."
        "It's empty right now, but it wouldn't be able to hold that many people."
        "Maybe there's another gym somewhere? This can't be it."
        "Whatever, let's start the workout before people swarm the equipment."
        "Hmm, I hear people approaching. Fuck I knew I wasn't going to get that lucky."
        s1 "Urgh, I feel so tired already. I'll be barely able to exercise."
        s2 "Oh, come on Olivia, gym is a place for you to reclaim your energy!"
        s1 "Okay, quick routine, but I need to head off after, Veronica."
        s1 "Alright, what should we get started on today?"
        s2 "How about we get started with some cardio first? And then maybe-"
        s1 "Hold on, Veronica. I think we've got an invited guest here."
        p "Uninvited? Sorry, what?"
        s1 "What are you even doing here?"
        s1 "Don't you know your place?"
        p "Whoa, hang on lady, what are you talking about?"
        p "I'm just trying to lift some weights."
        s1 "Who do you think you are, the boss of this gym?"
        s2 "Hey, Olivia, wait. I don't think he understands."
        "Hang on, this woman looks familiar..."
        p "Miss... Veronica?"
        s2 "..."
        s2 "[p]?"
        s1 "You know this guy?"
        s2 "He used to be one of my students!"
        s2 "[p], it's been a while, how are you doing now!"
        s2 "Oh, and it's {i}Mrs{/i} Veronica now."
        p "Whoa, congratulations- and yes, it has been a while."
        "Damn, I had such a huge crush on her back in school..."
        ver "This is my friend, Olivia. She's a lecturer at the local university."
        o "This is a woman's gym, didn't you know?"
        "Oooooooh. So that's why it's so small. It's not the main gym."
        p "I... did not know that. My bad."
        ver "Let him stay, Olivia. There are plenty of machines here to go around!"
        o "Why are you here anyway, [p]? Are you not a man?"
        o "Are you dickless?"
        p "I already said I didn't know it was a woman's gym. I'm sorry!"
        "Christ! What a bitch!"
        ver "Olivia!"
        ver "Sorry, [p]."
        o "I've wasted enough time already. I'm starting my workout."
        o "Feel free to keep your friend happy Veronica, I need to finish this workout quick and head off."
        ver "Alright, give me a call later."
        p "Miss- I mean, Mrs Veronica. Are you still teaching?"
        ver "Just call me Veronica, [p]. And yes, I'm still teaching. I love the profession."
        ver "What have you been up to since high school?"
        ver "I heard you left town for another university - you must be very successful!"
        ver "Have you graduated? Is that why you're back?"
        p "..."
        p "I guess I'm just taking a break from university. I missed the folks back home, so just thought I'd take a trip back home."
        ver "When will you be going back?"
        p "Haha... It's sort of a permanent break."
        ver "I see."
        ver "Well, like I said, Olivia is a local teacher at the university here. She teaches chemistry. Maybe something to consider?"
        p "You were always the best teacher back in highschool, Mrs. Veronica. Thanks for looking out for me. But somehow, I don't think Olivia's too fond of me."
        ver "Oh, don't mind her today. She just had a tough day."
        p "Yeah?"
        ver "Let me say sorry on her behalf. She's a very busy and very strict woman. I think she's dealing with a lot from the university side of things."
        ver "All of that has made her quite short."
        p "Ah that's alright. I didn't take it too personally. It's my fault anyway; I shouldn't have gone into the wrong gym."
        ver "No, no, [p], don't worry about that at all. To be honest, nobody comes here anyway, and like I said, there's plenty of machines to go around."
        ver "Think of it more as a private gym for us, than a woman's gym per se."
        p "Awesome! I'll pop in from time to time then, haha."
        p "Tell me something about yourself Mrs. Veronica."
        p "What's been going on?"
        ver "Just call me Veronica, you're not my student anymore!"
        p "Haha alright."
        ver "I teach at the same highschool, and I met a wonderful man and got married!"
        p "How'd you meet this guy?"
        ver "Oh, he's a travellimg businessman, and we met each other at the bar."
        p "Romantic!"
        ver "It was very exciting!"
        p "Are you guys, you know, settling down? Starting a family?"
        ver "Oh no, not yet. He's very busy, you see and away for a lot of the time. He says that once his job is more stable, he can finally settle down and we can think more about the future."
        p "Well, that sounds like a plan."
        ver "So, what are you working out today?"
        p "It's been a while since I've been back at the gym..."
        p "A little, then straight to bench press."
        p "And you?"
        ver "Cardio for me. A few minutes on the treadmill? I never felt too comfortable around the weights. Maybe in return for staying at the woman's gym you can teach us the bench press technique?"
        p "Sure thing, would be my pleasure."
        p "What were you guys doing before you came to the gym?"
        ver "Olivia and I love coming to the resort."
        ver "Usually, we walk to the resort and do a few exercises at the gym. Afterwards, we go to the sauna for a steam bath. We shower and then grab some tea at the resort. I love the routine."
        p "That actually sounds great. I'd love to say hi if I see you guys around in the future."
        "Maybe just Veronica, not Olivia."
        o "I don't know about that."
        o "I'm done, Veronica. Sorry, I'll have to skip out on you now, I've got something I need to attend to."
        ver "Oh don't worry about it, I'll see you next time. Take care okay?"
        "Olivia seems so brash and rude."
        "How is she such great friends with Veronica?"
        ver "She {i}is{/i} a bit short today."
        p "What's going on with her?"
        ver "I'm not too sure. She said something about having to meet the quota. It's something to do with chemistry and her work, no doubt."
        ver "I still think you should consider approaching her one day and see if she could help you out with university related things. Just... another day, not today."
        p "Haha, we'll have to see about that. Thanks."
        ver "Well, I'm going to do some cardio, then head off."
        p "Going to the sauna later?"
        ver "Maybe not today since Olivia's not coming."
        p "Fair enough. Talk to you later."
        "Damn, Veronica's still got it."
        "A lot of dudes from my class crushed on her, not just me."
        "Sad to see that she's found someone now and our fantasies will always be unfulfilled."
        "Or will they?"
        "Damn."
        "She must come to the gym a lot to stay in such great shape."
        "Okay, time to lift some heavy weights."
        "They say a man's strength increases two folds when a woman is watching."
        "Let's put that to the test."
        p "HURRR!!!"
        "Ah fuck! It's too heavy!"
        p "Hey, help! Help!"
        ver "Oh my god! Are you alright?"
        p "I am now. Guess I got a little bit carried away..."
        "How embarassing!"
        ver "Are you sure? You should take a break. Are you hurt anywhere?"
        p "I'm fine, thanks to you."
        ver "Maybe I should stay with you for a while. Just to make sure."
        p "You don't have any thing else to do later?"
        ver "I was going to spend some time with Olivia, but she's gone so I have a free schedule. Don't worry about it."
        ver "I've pretty much finished with my workout. Let me do a quick shower, then I'll meet you back at the reception resort, alright?"
        p "Thanks, I'll meet you there."
        "Did I just inadvertently score a date with my old teacher?"
        "Well done, [p]."
        "What a twist of fate, huh?"
        "I better hurry up and not keep her waiting."
        "Hmm... looks like someone left something behind... a note?"
        ## Hey bitch....
        scene letter
        "My god. Dantenol? Isn't that the new drug on the streets these days?"
        "And university lecturer... was this someone's note to Olivia?"
        "What has she gotten herself into? This might be useful for me to know one day."
        "I'll have to think more about this later."
