default uni_intro = False
label uni:
    if uni_intro == False:
        $ uni_intro = True
        "Veronica suggested that I could see Olivia and see if she could help me out with my studies."
        "But now that I'm seeing her again, she's hot, but damn does she look scary."
        "Alright, let's do this."
        p "Excuse me, Olivia."
        o "Class is over. Got any questions? Ask them next time."
        p "It's me, [p]. We met at the gym earlier?"
        o "Oh, it's you. The idiot that doesn't even what sex he is."
        p "Listen, I didn't mean to use the woman's gym and I'm sorry."
        o "What are you even doing here anyway? Can't you tell I don't like you?"
        p "..."
        p "I just need some help, please."
        p "I want to go to university again and get an education."
        o "That's good for you, [p]. But why do you think I care?"
        p "You're an educator, and I want to strive to better myself and learn new things."
        o "Stupid men like you can't learn. What a pointless exercise."
        "Wow, what a bitch."
        p "Are you sure about this?"
        o "You may leave now."
        p "..."
        p "You don't help me, and you don't even point me in the right direction."
        p "You don't even care about education. I know why you're really here."
        p "You dropped this letter in the gym."
        o "!!"
        p "You're just using university equipment to make drugs!"
        o "Y-You can't prove that!"
        p "If I reported this, what do you think will happen?"
        p "They'll go through the inventory and you'll go to prison."
        p "And the people you make the drugs for, I'm sure they've got friends in prison too."
        p "If you piss them off, you're done for."
        o "You, you!!"
        o "Argh!"
        o "What do you want from me?"
        p "I just want to get into the program here. I want to make my parents proud."
        o "Who do you think I am, [p]?"
        o "I can't get you into the program."
        p "Why not?"
        o "You can come to the lectures, but that's it."
        p "Going to the lectures isn't going to get me that piece of paper at the end."
        o "Sorry. Can't help you then."
        "Grrr..."
        "I {i}will{/i} get something in return, Olivia."
        o "What do you want, a handjob?"
        p "..."
        o "Hah! You're not getting anything from me, you perverted thing. If that's what you're after you may as well turn around."
        o "All men like you are the same."
        p "You talk big, Olivia, but I'm going to walk up to you now."
        p "And you're going to get on your knees."
        o "Get away from me, you vermin!"
        o "Any closer and I'll scream!"
        p "And when they come I'll show them the letter. You'll be finished."
        p "This is a small price to pay, no?"
        o "..!!"
        o "I. hate. you. And one day, you will regret everything."
        p "But not today. Go on, pleasure me."
        "Speechlessly, she got on her knees."
        "Shamefully, she looked down, yet maintained her defiant expression."
        ## forced fellatio
        p "That wasn't so bad, was it?"
        o "Fuck you. I hope you die in a fire!"
        p "I don't doubt for one moment you want me dead."
        p "I imagine you want me dead very much indeed, but unfortunately for you?"
        p "I have no intention of going anywhere, anytime soon."
        p "I own you now, Olivia."
        o "You, fucking monster!"
        o "How can you live with yourself, when you can rape a woman and feel nothing?!"
        p "You know what I hate about people like you, Olivia?"
        p "People like you act all high and mighty. You act so arrogant, like you're above us all."
        p "The only reason you're in this situation is because you're manufacturing drugs."
        p "You're no better than the scum-of-the-earth drug dealer."
        p "You make such addictive drugs, have you ever thought of the children who because of you, are now addicted?"
        p "Their lives ruined, relationships shattered..."
        p "Tell me, how do {i}you{/i} live with yourself?"
        o "..."
        p "Don't pretend you're anything more than a common whore."
        o "It's different!"
        p "Spare me, whore. Veronica told me that you were once damaged by a male."
        p "Make no mistake, what you faced then will be nothing compared to what I will do to you."
        p "From now on, you call me Master, and your name is no longer Olivia. Your name is now, Slut."
        p "Do you understand, Slut?"
        o "Go to hell."
        p "Still defiant? Even when I'm such a generous master?"
        p "Remember, I came to you for help and you pushed me away. Despite this, I am now offering you help."
        o "How the fuck is this helping me."
        p "I'm saving you from yourself. You're a broken doll, Slut. You need me."
        p "Without my good will, you'll be arrested, and raped and beat to death in prison, if you even make it there."
        p "Do you undestand now? You are my property."
        o "{i}Sob, sob...{/i}"
        p "I'll give you a night to mull it over. Your atittude had better change by tomorrow."
        $ daytime = 4
        $ daytimes = str(daytime)
        jump map

    if olivialvl == 1:
        $ olivialvl += 1
        p "Afternoon, Slut."
        o "..."
        p "I said, afternoon, Slut!"
        o "I do not answer to that name."
        p "You will, one day."
        p "What are the plans for you today?"
        p "..."
        p "I asked you a question."
        o "..."
        o "I'm a lecturer. I give classes."
        p "Don't be so curt with me, Slut."
        p "Do not forget, I'm impulsive. If you make me angry, I might just report you and end your life."
        o "...I understand."
        p "Master."
        o "Yes."
        p "Say it."
        o "...Master."
        p "Say the full phrase."
        o "..."
        o "I understand... master."
        p "Well done, Slut. That wasn't so hard, was it?"
        o "Fuck you."
        p "What was that?"
        o "..."
        p "You can try preserve your dignity, but I wonder how long it will last."
        p "Tell me Slut, what do you teach?"
        o "Chemistry."
        p "In front of many students?"
        o "Yes."
        p "Of course many students would come to class and stare at your body."
        p "You love the attention your body brings. It's why you go to the gym."
        "I've got a few ideas of how to have fun with Olivia."
        "But first, I'll need to make sure I have some supplies."
        "I should check out the sex shop in the online shop on the computer."
        "I need a dildo at least."
        jump map
    if olivialvl == 2:
        p "Slut."
        o "Hmph."
        p "We'll see how long you can keep that attitude up for."
        jump trainer
